[ENH] add inception time with example (from sktime-dl)
sktime/sktime pull request #3003
Opened 2022-07-14 09:50 UTC by tobiasweede

Adds InceptionTime classifier, network and the corresponding jupyter notebook with minor changes to work within sktime.

Don't know if you have plans to port everything from sktime-dl one-by-one or in a single big effort.
In the latter case, please just discard my PR.

2022-07-14 12:35 UTC, fkiraly commented
> Don't know if you have plans to port everything from sktime-dl one-by-one or in a single big effort.

I don't know about that for sure, I think we wanted to do it step by step? @TonyBagnall can tell you more.

In either case, any help is appreciated!

2022-07-15 08:28 UTC, fkiraly requested changes
Excellent, thansk for the port!

May I suggest one thing, to avoid unstructured clutter in the `examples` dir:
could you rename the notebook to sth that makes clear it is about classification, sub-topic neural networks? E.g., `02a_classification_deeplearning_inceptiontime`?

Or something similarly structured so that a lexicographic sort makes clear where it's from.
You may also like to think about order and naming in the context of the other notebook(s) you are adding - for instance, doesn't need to be 02 *a* as long as there is a consistent, logical order to things.

2022-07-17 18:51 UTC, fkiraly commented
@tobiasweede, FYI, the grid search has the `best_params_` attribute etc only after `fit` has been called.

2022-07-18 11:23 UTC, fkiraly commented on sktime/utils/data.py
> +def check_and_clean_data(X, y=None, input_checks=True):
much of this seems redundant with functionality now in `datatypes`.
Have a look at `convert_to`.

Also, if this is specific to neural networks, should it live in `networks`?

2022-07-18 11:26 UTC, fkiraly commented
FYI, I do not consider the "refactor" comments as blocking.
What I would consider blocking is my suggestion to localize the specific checks as private, in the same file or module as the estimator, so we do not duplicate existing utilities modules. We can refactor to `convert_to` etc later. Or, you could refactor/replace now, as said the "refactor" part is not blocking.

2022-07-18 16:33 UTC, tobiasweede commented
@fkiraly Thank you for you comments. I will work on the case and try to address the issues.

I also plan show up at a collab code session.
Probably not this Friday, but during the next weeks...

2022-07-18 17:24 UTC, fkiraly commented
> I also plan show up at a collab code session.

Nice, looking forward to that!
Would be appreciated if you send a message on the slack contributors channel a few days ahead, so the people interested in neural networks know.

2022-12-03 06:47 UTC, achieveordie commented
Hey, @tobiasweede Are you still working on this? We could really make use of `InceptionTime` in `sktime`. It'll be incredibly helpful, thanks!

2023-04-15 19:09 UTC, fkiraly commented on sktime/classification/deep_learning/inceptiontime.py
> +        self._is_fitted = True
I removed this

2023-04-15 19:09 UTC, fkiraly commented on sktime/utils/data.py
> +def check_and_clean_data(X, y=None, input_checks=True):
I replaced this

2023-04-15 19:10 UTC, fkiraly commented
I've taken the freedom to wrap this up.
FYI @gaudium

2023-04-16 11:49 UTC, fkiraly approved these changes
all fixed up now

2023-04-16 11:50 UTC, merged

2023-04-17 20:50 UTC, phylopylo commented
I have tested the InceptionTimeClassifier and confirmed that it runs without error.