[DOC] clarifications on deprecation notes
sktime/sktime pull request #3411
Opened 2022-09-12 08:17 UTC by fkiraly

This adds clarifications and a worked example to the deprecation policy.

The policy itself does not change, only clarifying details are added.

2022-09-16 08:32 UTC, TonyBagnall requested changes
Do we still have the distinction between module development status? It was something like experimental, progressing and mature? (cant remember the exact terms). If we are keeping that distinction, it would be good to clarify the deprecation policy related to different statuses, because as I understand it experimental modules do not currently require deprecation

2022-09-18 20:08 UTC, fkiraly commented
@TonyBagnall, to the best of my knowledge, there has never been a distinction in the documented ("official") deprecation policy based on "maturity status".

We were generally watching out for public interfaces not getting broken.

So, introducing such a distinction would be a change to the deprecation policy - which is outside the scope of this pull request. This PR just clarifies the existing policy.

2022-09-26 09:10 UTC, TonyBagnall commented
@fkiraly is there still an "unofficial" distinction in policy for the deprecation policy for stable/maturing/experimental modules as defined here? https://github.com/alan-turing-institute/sktime/blob/main/README.md in the past we have not required a full cycle to deprecate code in experimental modules. Is this policy changing?

2022-09-26 09:31 UTC, fkiraly commented
> in the past we have not required a full cycle to deprecate code in experimental modules

I can remember this only for *private* modules.

Generally, we should not break any interfaces that someone could be using subject to common conventions ("public means stable") if we can avoid it.

2022-09-26 10:17 UTC, TonyBagnall commented
it definitely was the case that experimental did not require full deprecation, I remember distinctly with the clustering module. Thank you for clarifying that this is no longer the case though.

2022-09-28 23:01 UTC, fkiraly commented
> it definitely was the case that experimental did not require full deprecation, I remember distinctly with the clustering module. Thank you for clarifying that this is no longer the case though.

"was the case", I suppose you mean that PR got merged without proper deprecation in that module.
That sounds more like a mistake (or lenience) than an actual policy.

Either way, would appreciat if you comment whether the change request still needs action, as the discussion does not seem to have to do with the scope of this PR = making the existing rules clearer.

2022-09-29 15:05 UTC, TonyBagnall approved these changes

2022-10-01 20:10 UTC, merged