added basic simulate feature for base class and statsmodels
sktime/sktime pull request #3462
Opened 2022-09-22 13:29 UTC by ltsaprounis

#### Reference Issues/PRs

fixes #3461 

#### What does this implement/fix? Explain your changes.

Prototype for simulate method in forecaster base class with a statsmodels implementation.

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2022-10-25 11:03 UTC, ltsaprounis commented
Results from simply adding the simulate method in the PREDICT_METHODS list in `BaseForecaster._vectorize`

```python
import numpy as np
import pandas as pd

from sktime.forecasting.ets import AutoETS
from sktime.datasets import load_airline
from sktime.utils.plotting import plot_series

y = load_airline().to_frame()
y_hier = (
    pd.concat([y.assign(ts_id="ts_1"), y.assign(ts_id="ts_2")])
    .set_index("ts_id", drop=True, append=True)
    .reorder_levels(["ts_id", "Period"])
)

forecaster = AutoETS()
forecaster.fit(y_hier)

y_hat = forecaster.simulate(np.arange(1,12)) 

display(y_hat)
```
![image](https://user-images.githubusercontent.com/64217214/197756659-3b1e7a90-a952-4373-a938-fd2c95c7116c.png)

still WIP, but looking promising!

2022-10-27 09:06 UTC, ltsaprounis commented
Look at all these tests failing in the CI!

![image](https://user-images.githubusercontent.com/64217214/198242494-a912e546-4867-4488-a8c1-ec26910b67a4.png)

2022-10-27 10:47 UTC, ltsaprounis commented
HA! some estimators already have a simulate method!
1. [UnobservedComponents](https://github.com/sktime/sktime/blob/29209ecabce57e3586ee0a7121b7c19101f2f56b/sktime/forecasting/structural.py)
2. [DynamicFactor](https://github.com/sktime/sktime/blob/29209ecabce57e3586ee0a7121b7c19101f2f56b/sktime/forecasting/dynamic_factor.py)

2022-10-28 10:34 UTC, ltsaprounis commented
This error is unrelated and really strange...
[FAILED sktime/transformations/series/tests/test_clear_sky.py::test_clearsky_trafo_vals - urllib.error.HTTPError: HTTP Error 503: SERVICE UNAVAILABLE](https://github.com/sktime/sktime/actions/runs/3344084474/jobs/5538139324#step:7:1689)

2022-10-31 12:10 UTC, ltsaprounis commented
There's an issue with the statsmodels prediction index for integer index not starting from 0. 
I've raised an issue and PR there to fix it upstream (https://github.com/statsmodels/statsmodels/pull/8488), but might add a temp fix here with a warning to make this feature available here a bit sooner and not high lower bound on statsmodels only because of this.

2022-11-01 17:24 UTC, ltsaprounis commented
![image](https://user-images.githubusercontent.com/64217214/199297524-dd6ba905-c8f3-4a73-b47e-2053aba9a007.png)

2022-11-10 21:52 UTC, fkiraly requested changes
[removed earlier version since not a real review]

2022-12-02 17:52 UTC, miraep8 commented
@fkiraly  - dismissing previous review as I don't think that it was pertinent to this PR. @ltsaprounis I would be happy to review this PR when it is ready for review.  See it is still marked as a draft PR, but feel free to ping me when ready to be checked out!

2022-12-02 23:39 UTC, fkiraly requested changes
Sure.

* I would like a discussion of one point (here or in a STEP, as this is a base class interface): Why should this be part of the base class? It seems like most examples in this proof-of-concept have extra parameteres that are specific for the simulator and are not used by any other method. That indicates we should compare this to an alternative design where this is not a method of a forecaster, but we have a simulator/sample base class, that a forecaster can return when fitted? This would also allow simulators that are not coming from forecasters, e.g., Brownian motion with fixed parameters.
* we should also test the vectorized case(s), I would do that separate from the test suite only once or a few time for selected forecasters, like the tests in `test_base` for vectorized forecasts.

2023-01-28 19:15 UTC, ltsaprounis commented
I will no longer work on this project. See #4152

2023-01-30 23:25 UTC, fkiraly commented
seems useful as a basis for a simulator interface, I'll reopen as a draft

2024-03-08 20:19 UTC, closed without merging