[EHN] Parallelized `evaluate` with {joblib, dask}
sktime/sktime pull request #3511
Opened 2022-10-01 07:38 UTC by topher-lo

#### What does this implement/fix? Explain your changes.
- Parallelizes `evaluate` with two possible backends: `joblib` and `dask`
- Adds flag `compute` which is set to True returns a lazy dask DataFrame (if backend is set to "dask")

#### Does your contribution introduce a new dependency? If yes, which one?
Soft dependencies: `dask==2022.8.0` and `distributed==2022.8.0`

#### What should a reviewer concentrate their feedback on?

#### Any other comments?

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

2022-10-08 07:35 UTC, topher-lo commented
@fkiraly What''s the protocol for adding soft dependencies? Should `dask` be added to a separate dependency group e.g. `distributed`?

2022-10-08 08:01 UTC, topher-lo commented on sktime/forecasting/model_evaluation/_functions.py
> +        Only applied if backend is to set "dask". If set to True, returns
```suggestion
        Only applied if backend is to set "dask". If set to True, returns `dd.DataFrame`
```

2022-10-11 20:35 UTC, fkiraly commented
protocol for soft dependencies here:
https://www.sktime.org/en/stable/developer_guide/dependencies.html

Generally, all tests must pass without soft dependencies installed, or be decorated with skipif or internal check that avoids the import if not present.

2022-10-11 22:22 UTC, fkiraly commented
https://github.com/sktime/sktime/pull/3542 is now merged (unlocking dependencies in grid search and reduction) - let me know if I should help integrate.

2022-10-16 04:40 UTC, topher-lo commented
@fkiraly All tests are passing except 1 "doctest" (https://github.com/sktime/sktime/actions/runs/3258070873/jobs/5349886697). Haven't seen this before and the code quality check / pre-commits didn't pick this one up. Can you help out with this?

After that, I think this PR is good to go!

2022-10-16 12:08 UTC, fkiraly commented
excellent - looks good to go?

2022-10-17 02:26 UTC, topher-lo commented
@fkiraly Good to go. We should run benchmarks with the M3 / M4 datasets and this parallelized evaluate. I can help turn this into a blog post as well.

2022-10-20 15:54 UTC, chillerobscuro commented
When starting fresh with a new copy of this branch, I'm getting a circular import error. I can run the following code only if I comment out line 19 from sktime/forecasting/model_selection/_tune.py, but that presumably limits functionality from _tune.py. (Commented out line is `from sktime.forecasting.model_evaluation import evaluate`)
```
from sktime.datasets import load_airline
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.naive import NaiveForecaster

y = load_airline()
forecaster = NaiveForecaster(strategy="mean", sp=12)
cv = ExpandingWindowSplitter(initial_window=12, step_length=3, fh=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
results = evaluate(forecaster=forecaster, y=y, cv=cv)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b8e7e546881f> in <module>
      1 from sktime.datasets import load_airline
      2 
----> 3 from sktime.forecasting.model_evaluation import evaluate
      4 
      5 from sktime.forecasting.model_selection import ExpandingWindowSplitter

~/Code/opensource/sktime/sktime/forecasting/model_evaluation/__init__.py in <module>
      7 __all__ = ["evaluate"]
      8 
----> 9 from sktime.forecasting.model_evaluation._functions import evaluate

~/Code/opensource/sktime/sktime/forecasting/model_evaluation/_functions.py in <module>
     18 from sktime.exceptions import FitFailedWarning
     19 from sktime.forecasting.base import BaseForecaster, ForecastingHorizon
---> 20 from sktime.forecasting.model_selection._split import BaseSplitter
     21 from sktime.utils.validation.forecasting import check_cv, check_scoring
     22 

~/Code/opensource/sktime/sktime/forecasting/model_selection/__init__.py in <module>
     20 from sktime.forecasting.model_selection._split import SlidingWindowSplitter
     21 from sktime.forecasting.model_selection._split import temporal_train_test_split
---> 22 from sktime.forecasting.model_selection._tune import ForecastingGridSearchCV
     23 from sktime.forecasting.model_selection._tune import ForecastingRandomizedSearchCV

~/Code/opensource/sktime/sktime/forecasting/model_selection/_tune.py in <module>
     17 from sktime.exceptions import NotFittedError
     18 from sktime.forecasting.base._delegate import _DelegatedForecaster
---> 19 from sktime.forecasting.model_evaluation import evaluate
     20 from sktime.utils.validation.forecasting import check_scoring
     21 

ImportError: cannot import name 'evaluate' from partially initialized module 'sktime.forecasting.model_evaluation' (most likely due to a circular import) (/Users/loganduffy/Code/opensource/sktime/sktime/forecasting/model_evaluation/__init__.py)
```

2022-10-22 22:25 UTC, fkiraly commented
I can confirm @chillerobscuro's bug - it happens on this branch, and not on `main` (python 3.8, windows).

I suggest we add it as a one-off test and see what happens?

2022-10-22 22:25 UTC, fkiraly requested changes
Looks great!

We need to find out though why this bug is appearing.

2022-10-22 22:31 UTC, fkiraly commented
I think it is all the imports that this PR added in `model_evaluation._functions` for typing, especially

```python
from sktime.forecasting.model_selection._split import BaseSplitter
```

I think you asked a while ago why we do not use typing everywhere, @topher-lo? I forgot one reason - risk of circular imports.

Let's minimize imports that introduce unnecessary coupling (worst case, circular imports).

Can we get to having the same imports as before?

2022-10-23 12:52 UTC, topher-lo commented
Ahh it just be due to the typing. Thanks for the heads up here @fkiraly. I'm currently travelling as well. Will revert the changes first thing next week.

2022-10-30 15:01 UTC, fkiraly requested changes
I wanted to merge for the release but noticed this was failing dependency isolation tests, then I noticed some other things. I think we need to delay this to 0.14.1, apologies.

* dependency `dask` was not isolated. Full test suite should run if `dask` is not present. Made some proposed changes in latest commit, kindly check whether you are happy with that.
* `"loky"` and `"multithreading"` options don't seem to do anything, this does not seem right. Probably should be passed to `joblib`?
* `dask` is not used in `"update"` mode, is that correct?
* docstring was incomplete, this should properly describe what happens for what argument. I tried to fill in but cannot, since I am not sure what should happen in the `"update"` case or `"multithreading"` case, i.e., if the current behaviour that can be reverse engineered is a bug or intentional.

2022-10-31 10:10 UTC, topher-lo commented
> * dependency `dask` was not isolated. Full test suite should run if `dask` is not present. Made some proposed changes in latest commit, kindly check whether you are happy with that.
👍 
> * `"loky"` and `"multithreading"` options don't seem to do anything, this does not seem right. Probably should be passed to `joblib`?
https://github.com/sktime/sktime/pull/3511/commits/4097494cff757e73ce3e434bb3db8699650e94c6
> * `dask` is not used in `"update"` mode, is that correct?
Correct. In fact, no parallelization joblib or dask is used in update mode (unit tests for update would fail otherwise).
> * docstring was incomplete, this should properly describe what happens for what argument. I tried to fill in but cannot, since I am not sure what should happen in the `"update"` case or `"multithreading"` case, i.e., if the current behaviour that can be reverse engineered is a bug or intentional.
https://github.com/sktime/sktime/pull/3511/commits/85083112d0e569eae6fddd7a085815426f4ba25e

2022-11-02 23:02 UTC, fkiraly commented
> Correct. In fact, no parallelization joblib or dask is used in update mode (unit tests for update would fail otherwise).

Hmmm, can you explain why that is the case?

2022-11-02 23:02 UTC, fkiraly submitted a review, later dismissed
Looks like all resolved, thanks!

2022-11-03 08:46 UTC, topher-lo commented
> > Correct. In fact, no parallelization joblib or dask is used in update mode (unit tests for update would fail otherwise).
> 
> Hmmm, can you explain why that is the case?

Because update must work sequentially (from one window to the next on the same estimator), but parallel execution will fit different windows on unfitted estimators simultaneously.

2022-11-03 22:00 UTC, fkiraly commented
oh, of course.

2022-11-03 22:46 UTC, merged