[ENH] Classifier Notebook sklearn Examples
sktime/sktime pull request #3523
Opened 2022-10-03 12:29 UTC by MatthewMiddlehurst

Adds sklearn model selection and cross-validation examples to the classification notebook (#2116, #2132).

Cleans up the notebook a bit, i.e. faster parameters, typos.

2022-10-03 15:27 UTC, fkiraly submitted a review, later dismissed
question: why are we replacing `tsfresh` by `catch22`? The former is more popular afaik.

2022-10-03 15:28 UTC, MatthewMiddlehurst commented
It is faster and less verbose, it is minor, so I don't mind reverting.

2022-10-03 15:31 UTC, MatthewMiddlehurst commented
unrelated, but TapNet is breaking the macOS test and apparently takes 10 minutes per test

2022-10-03 15:31 UTC, fkiraly commented
maybe add `tsfresh` as another example and say fit/predict works the same, just don't run it in the notebook

2022-10-03 15:32 UTC, fkiraly commented
> unrelated, but TapNet is breaking the macOS test and apparently takes 10 minutes per test

can you please report? This passed in the PR

2022-10-03 15:40 UTC, fkiraly commented
other question: is it correct that the sklearn wrapped classifiers won't accept the pandas formats, or cannot be used themselves in pipelines?

Should we hence not have sktime grid search compositors for classification?

2022-10-03 15:44 UTC, MatthewMiddlehurst commented
Unsure how it would fit into a pipeline, output should be the same as normal sklearn estimators

2022-10-03 16:21 UTC, TonyBagnall commented
existing typo "utiltiy" to correct ""Under the hood, `sktime`'s `make_pipeline` utiltiy dispatches to right pipeline"

2022-10-03 16:40 UTC, TonyBagnall requested changes

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
>      "We demonstrate the simplest use cases for classifiers and demonstrate how to build bespoke pipelines for time series classification.\n",
change one demonstrate to show

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "`sktime` contains the state of the art in time series classifiers in the package classification. These are grouped based on their representation. An accurate and\n",
dont need this newline after an accurate and

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "Most classifiers in `sktime` involve some degree of transformation. The simplest form is simply consisting of a pipeline of transformation (aka \"feature extraction\") followed by an `sklearn` c
The simplest form consists of a

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "The `sktime` `make_pipeline` utility allows to combine transformers and classifiers into a simple pipeline. The classifier pipelined can be an `sktime` time series classifier, or an `sklearn` ta
utility allows the combination of transformers and classifiers

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "`sktime` offers two other ways of solving multivariate time series classification problems:\n",
"solving multivariate time series problems" to "building estimators for multivariate time series problems"

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> -    "We can also fit one classifier for each time series column and then aggregated their \n",
and then aggregated -> and then aggregate

2022-10-03 16:40 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "One nearest neighbour (1-NN) classification with Dynamic Time Warping (DTW) is one ofthe oldest TSC approaches, and is commonly used as a performance benchmark.\n",
one of the oldest

2022-10-04 14:49 UTC, TonyBagnall approved these changes

2022-10-05 08:23 UTC, TonyBagnall commented
contributes to https://github.com/sktime/sktime/issues/1549

2022-10-14 15:08 UTC, TonyBagnall commented
> maybe add `tsfresh` as another example and say fit/predict works the same, just don't run it in the notebook

@fkiraly I think this change has been made, could you unblock or let us know if there are other changes you want please? thanks.

2022-10-25 22:39 UTC, merged