[BUG] Fix pipeline tag for NaN values
sktime/sktime pull request #3549
Opened 2022-10-08 16:25 UTC by aiwalter

closes #3547

2022-10-08 18:33 UTC, ngupta23 commented
Thanks @aiwalter . I am not sure what the best solution would be in this case. The tag for handling missing data is set to True, but this assumes that there is an imputer in the pipeline (which the user must add). Also, even if there is an imputer, some subsequent transformation step may introduce NA values. The onus is on the user to make sure that the pipeline will impute missing values appropriately and and I am ok with that responsibility being put on the user.

2022-10-08 19:48 UTC, fkiraly requested changes
Oops - I suppose that was a mistake since we indeed can have an imputer.

Do I understand correctly that this sets the "handles missing data" tag to `True` no matter what? It is a fix but the tag will be incorrect for some pipelines.

I don't mind as a temporary fix, but a more prinipled fix should be not too difficult:
The cleaner way would be using `_tagchain_is_linked_set` as in lines 208ff in `TransformerPipeline`.

2022-10-08 19:49 UTC, fkiraly commented
> Thanks @aiwalter . I am not sure what the best solution would be in this case. The tag for handling missing data is set to True, but this assumes that there is an imputer in the pipeline (which the user must add). Also, even if there is an imputer, some subsequent transformation step may introduce NA values. The onus is on the user to make sure that the pipeline will impute missing values appropriately and and I am ok with that responsibility being put on the user.

@ngupta23, we have a tag that says whether the transformer removes all NA. Indeed transformers may produce NA (and there is no tag for that), but at least we can check that the transformers preceding the first transformer removing NA can handle NA (see above).

2022-10-08 20:12 UTC, fkiraly commented
also, kindly add the (simplest possible version of) example from #3547 to `test_pipeline`

2022-10-09 01:00 UTC, aiwalter commented
@fkiraly I think adding test should not be part of this PR. Its a bigger topic to add generic tests for compositions. I dont want to add a test for just one particular case.

2022-10-09 01:38 UTC, fkiraly commented
> I dont want to add a test for just one particular case.

My recommendation: just copy-paste @ngupta23's code so we know we fixed it, and we don't regress.

We can think about more general tests later.

2022-10-09 12:59 UTC, aiwalter commented
I have tested it locally and it works now

2022-10-09 15:56 UTC, fkiraly commented
> I have tested it locally and it works now

That's not the same. We need to make sure that future changes don't break it again, that we can do only if we add it as a test case.

E.g., let's say we introduce the "advanced" handling of the tag, how would we know we didn't break @ngupta23's use case?

General best practice: if you fix a bug, include a test that "certifies" the fix.

2022-10-09 22:26 UTC, fkiraly commented
thanks, @aiwalter  :-)
@ngupta23's examples have saved us a number of times from breaking things in updates...

2022-10-10 23:45 UTC, fkiraly approved these changes
Thanks!

2022-10-10 23:45 UTC, merged