[DOC] Replace `sphinx-panels` with `sphinx-design`
sktime/sktime pull request #3575
Opened 2022-10-12 09:53 UTC by MatthewMiddlehurst

Replaces the `sphinx-panels` dependency with `sphinx-design` #3370.

The cards/panels are slightly smaller than before, and the button colour has changed since the default grey bugged out on darkmode for me with the new package.

2022-10-14 15:06 UTC, TonyBagnall approved these changes

2022-10-15 22:11 UTC, fkiraly requested changes
Why is this needed? What does it improve?

2022-10-15 22:13 UTC, MatthewMiddlehurst commented
See #3370. You gave it a thumbs up, so I assumed you agreed with the change.

2022-10-17 00:17 UTC, RNKuhns commented
@MatthewMiddlehurst I'll give this a review in the next day.

@fkiraly the `sphinx-panels` package that has been used in the `sktime` documentation is no longer maintained. `sphinx-design` provides similar functionality and is suggested as an alternative by [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/index.html). Plus `sphinx-design` looks nice (IMHO).

2022-10-17 07:15 UTC, fkiraly commented
ah yes, I remember, thanks. Was confused by the PR text which said something about panels being smaller, which struck me odd as a reason for a change, but you have to follow the link to #3370. Please consider this unblocked (but not approved)

2022-10-17 07:16 UTC, fkiraly commented
any chance to get this working using `sphinx-design`?
https://github.com/sktime/sktime/pull/3211

Using `sphinx-panels`, it was impossible to get two buttons on a panel and have both work.

2022-10-18 10:37 UTC, achieveordie commented
LGTM

2022-10-22 20:21 UTC, MatthewMiddlehurst commented
@RNKuhns do you still intend to review this? Not rushing you to do so if you are.

2022-10-23 16:49 UTC, RNKuhns approved these changes
@MatthewMiddlehurst this looks good to me and the new buttons point to the same places as the old buttons. I think we should be able to merge this.

I did make one comment on the label for the "User Guide" on the index. It is really pointing to the "User Documentation". But you maintained the prior label, so maybe we shouldn't change that as part of this PR.

2022-10-23 16:49 UTC, RNKuhns commented on docs/source/index.rst
> +        User Guide
This is really pointing to the broader category of "User Documentation". Could consider changing these labels to "User Documentation" from "User Guide". But this PR does successfully convert to sphinx-design and retain the original label.

2022-10-24 08:57 UTC, merged