[ENH] Option to fit `Clearsky` transformer in parallel
sktime/sktime pull request #3652
Opened 2022-10-26 16:31 UTC by ciaran-g

#### Reference Issues/PRs

No specific issue

#### What does this implement/fix? Explain your changes.

Option to fit the `ClearSky` transformer in parallel
* This is done with joblib
* Updated the docstrings with new options

#### Does your contribution introduce a new dependency? If yes, which one?

No

2022-10-26 16:57 UTC, MatthewMiddlehurst commented
Is the output `self.clearskypower` the same with the new code as it was previously? I assume so, but good to check.

There is a bit of inconsistency with the new doc options vs the old, i.e. `min_thresh : float, default=0` vs `n_jobs: int, optional (default=None)`. I don't believe there is a consistent way to do it throughout the package, but it should be consistent in the same file at least.

2022-10-26 17:00 UTC, MatthewMiddlehurst commented
Unrelated to this PR specifically, but we should probably add a `backend` parameter to other estimators which use joblib and start using the `prefer` argument. May require some evaluation to determine which backend if preferred for each, though.

2022-10-27 09:46 UTC, fkiraly commented
FYI @topher-lo, re (in)consistency with current efforts to introduce `dask` and multiprocessing?

2022-10-28 11:45 UTC, ciaran-g commented
> Is the output `self.clearskypower` the same with the new code as it was previously? I assume so, but good to check.

Added a wee check for this

> There is a bit of inconsistency with the new doc options vs the old, i.e. `min_thresh : float, default=0` vs `n_jobs: int, optional (default=None)`. I don't believe there is a consistent way to do it throughout the package, but it should be consistent in the same file at least.

Updated the docstrings 👍

2022-10-28 11:55 UTC, MatthewMiddlehurst submitted a review, later dismissed
Looks good assuming all the tests pass. Won't merge this week due to the release, and ill give a bit of time for others to comment if they want.

FYI there appears to be an issue with the data loaded in the test currently, see #3663. Won't request any changes in this PR for that though unless you want to make them yourself.

2022-10-28 12:01 UTC, ciaran-g commented
> FYI there appears to be an issue with the data loaded in the test currently, see #3663. Won't request any changes in this PR for that though unless you want to make them yourself.

Hmm ok, maybe for the tests it would make sense to just store the data in a csv file or something and load them that way rather than calling the api?

2022-10-28 12:16 UTC, MatthewMiddlehurst commented
Yes, `sktime.data.datasets` contains some dataset files used mostly for testing, but not this one possibly? If none of the already present datasets fulfil the requirements for the test, it may be worth adding it.

2022-10-28 12:18 UTC, MatthewMiddlehurst commented
i.e. `load_unit_test` will load the file from there.

2022-10-28 16:20 UTC, ciaran-g commented
> Yes, `sktime.data.datasets` contains some dataset files used mostly for testing, but not this one possibly? If none of the already present datasets fulfil the requirements for the test, it may be worth adding it.

Added the local dataset and the option for loading it via `load_solar(api_version=None)`. Also made some changes to use the new file in the tests for `load_solar`

2022-10-28 16:21 UTC, ciaran-g commented
> 



> Looks good assuming all the tests pass. Won't merge this week due to the release, and ill give a bit of time for others to comment if they want.

Any wiggleroom on this? Would be keen for it to be in the new release to make sharing the update easier

2022-10-28 16:31 UTC, MatthewMiddlehurst submitted a review, later dismissed
Those changes look good to me. `test_load_solar` may still run in to the same issue, but that's not a problem for this PR.

At this stage I'm pretty sure only PRs required for the release will go in, sorry.

2022-10-29 18:14 UTC, fkiraly requested changes
There would be wiggle room, but it seems like the tests are failing, sth around loading the dataset?
We need to understand what is going on here before we merge, so it will probably not go in 0.14.0.

2022-10-29 18:14 UTC, fkiraly commented on sktime/transformations/series/clear_sky.py
> -    quantile_prob : float, default=0.95
I think there should be a space on both sides. Currently not testing but it's numpydoc style afaik

2022-10-29 18:28 UTC, fkiraly approved these changes
Hm, the failure seems to be unrelated to this PR, so this can be merged.

But, can you kindly check the bug separately then, @ciaran-g?

2022-10-29 21:21 UTC, fkiraly requested changes
I think I was wrong, the failures seem genuinely related to the csv added in this PR?

2022-10-31 10:17 UTC, topher-lo commented
> FYI @topher-lo, re (in)consistency with current efforts to introduce `dask` and multiprocessing?

No inconsistency. The idea that we should have a standard `backend` argument across all parallelized estimators (unless we decide that only "threading" should be used e.g. for code that readily releases the GIL) is great. Also having `prefer="threading"` is generally a good idea for most data science situations (unless we know beforehand that the code is GIL hungry e.g. in `evaluate`).

@MatthewMiddlehurst Perhaps we should start a GitHub issue tracker for all uses of joblib so far? Try to standardize the signatures across `sktime`.

2022-10-31 11:19 UTC, ciaran-g commented
> There would be wiggle room, but it seems like the tests are failing, sth around loading the dataset? We need to understand what is going on here before we merge, so it will probably not go in 0.14.0.

No worries, I hard-coded the path to the csv so it would only work on windows (lol) should be fixed now!

2022-11-02 23:00 UTC, fkiraly approved these changes
Looks good now, hopefully fixes the loader test failure?

2022-11-02 23:01 UTC, merged