[BUG] exclude TapNet to test CI
sktime/sktime pull request #3812
Opened 2022-11-18 09:57 UTC by TonyBagnall

Tests are failig for strange reasons, see for example
https://github.com/sktime/sktime/actions/runs/3492869189/jobs/5847895424
I cannot reproduce locally. TapNet was excluded but recently put back in. This PR is just to test to see if it is the root of the problem

2022-11-18 12:01 UTC, MatthewMiddlehurst approved these changes

2022-11-18 18:23 UTC, fkiraly requested changes
Please add an issue number to the comment before we merge this

2022-11-18 23:26 UTC, MatthewMiddlehurst approved these changes

2022-11-18 23:26 UTC, merged

2022-11-19 06:28 UTC, achieveordie commented
Couldn't find any errors related to TapNet in the job, will follow this issue though