fix: pre-commit errors
sktime/sktime pull request #3881
Opened 2022-12-03 20:13 UTC by nilesh05apr

#### Reference Issues/PRs
Fixes #3351. See also #3365 

#### What does this implement/fix? Explain your changes.
Migrating dl estimators from sktime_dl to sktime

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
tests

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

2022-12-05 06:46 UTC, achieveordie requested changes
Some minor typos are resulting in current failures in checks. Let's get them sorted so this estimator passes through.

2022-12-05 06:46 UTC, achieveordie commented on sktime/networks/resnet.py
> +_check_soft_dependencies(
Any reason to have this here? I don't think you're making use of the import anywhere. This estimator can run without having `keras-self-attention` as a soft-dep.

2022-12-05 06:46 UTC, achieveordie commented on sktime/networks/resnet.py
> +        _check_soft_dependencies(
Refer to the initial point.

2022-12-05 06:46 UTC, achieveordie commented on sktime/networks/resnet.py
> +    def build_model(self, input_shape, **kwargs):
The abstract method that all estimators implement is `build_network()`. This minor reason is why tests are failing across all runners. A small typo :)

2022-12-05 06:46 UTC, achieveordie commented on sktime/classification/deep_learning/resnet.py
> +"""Multi Layer Perceptron Network (MLP) for classification."""
"Residual Network (ResNet) for classification" would be more accurate.

2022-12-05 06:46 UTC, achieveordie commented on sktime/classification/deep_learning/resnet.py
> +    >>> clf.fit(X_train, Y_train) # docktest: +SKIP
`# doctest: +SKIP` to have them skipped, another small typo is causing doctest failure in the checks.

2022-12-05 06:49 UTC, achieveordie commented
You could go through the tests to see if there are any failures that I missed. LMK if you need any help. This is almost done, great work!

2022-12-06 12:43 UTC, nilesh05apr commented
@achieveordie can you please review test results? it is failing for assertion error. Thank you

2022-12-06 13:11 UTC, achieveordie commented
Regarding `AssertionError` in [test_fit_does_not_overwrite_hyper_params](https://github.com/sktime/sktime/actions/runs/3620372174/jobs/6117748811#step:7:1610):

An excellent way to see what went wrong is to check what the error is, here it says: 

> AssertionError: Estimator ResNetClassifier should not change or mutate  the parameter optimizer from None to <keras.optimizers.optimizer_experimental.adam.Adam object at 0x7fbc8d5f2470> during fit.

which makes sense since we don't want to change parameters passed by the user. For that purpose, we actually use `self.optimizer_` (and not `self.optimizer`) as the parameter we set in case the user doesn't provide any value. You can check out [any](https://github.com/sktime/sktime/blob/main/sktime/classification/deep_learning/cnn.py#L141) of the accepted estimators to compare your own model since the only change thing that changes is the actual implementation of the estimator, the mechanics remain similar, if not the same.

2022-12-06 13:22 UTC, achieveordie commented
(While we are still changing things, another easy win is renaming `lr` to `learning_rate` in the same line to avoid [this](https://github.com/sktime/sktime/actions/runs/3620372174/jobs/6117749271#step:10:795) warning.)

2022-12-07 10:53 UTC, achieveordie approved these changes

2022-12-11 02:17 UTC, merged