[ENG] Evaluate function to accept list of scorers
sktime/sktime pull request #3883
Opened 2022-12-04 17:56 UTC by aiwalter

#### What does this implement/fix? Explain your changes.
Function `from sktime.forecasting.model_evaluation import evaluate` to accept list of scorers, this is then added as new columns to the output data.

2022-12-04 20:45 UTC, RNKuhns commented
@aiwalter this will be a nice incremental increase in functionality. I'll review once out of draft.

2022-12-31 00:15 UTC, fkiraly commented on sktime/forecasting/model_evaluation/_functions.py
> +from sktime.forecasting.model_selection._split import BaseSplitter
risk of circular imports, I would recommend to avoid doing this

2022-12-31 00:16 UTC, fkiraly requested changes
Makes sense.

The "returns" section in the docstring should document the change properly.

2023-01-10 11:18 UTC, fkiraly approved these changes
Thanks for completing the docstring.

2023-01-10 11:19 UTC, merged