[GOV] Remove ability of CC to overrule core dev decisions
sktime/sktime pull request #3937
Opened 2022-12-14 15:58 UTC by aiwalter

Reference Issues/PRs
https://github.com/sktime/sktime/issues/3865

What does this implement/fix? Explain your changes.
Remove ability of CC to overrule decisions made by core devs.

2022-12-14 16:08 UTC, aiwalter commented
a core dev vote was invoked on this PR and will end 21. December

2022-12-14 16:17 UTC, GuzalBulatova requested changes
I think that CC should have rights to overrule core-devs decisions, given the consensus/ majority of CC agree that another decision has to be made and provide reasoning behind the overrule.

2022-12-14 18:11 UTC, fkiraly commented
This PR (and its predecessor) has violated governance rules on how to vote multiple times.

* gov rules clearly say, we vote publicly. Martin opened votes in private.
* Martin has used some app to vote anonymously in a private slack channel that had people in it who were not eligible to vote.
* this is a substantial change so would formally require a STEP, which implies 7 days discussion period.

Further, we are violating the "spirit" of how to vote.

* some people are now on holiday and will be unable to vote until they return.
* some people wanted to pause from votes after this and will not see the second vote in time.

I think we should just stop this and base the changes on consensus.

I.e., start over in January when everyone is back from holidays or pause.
Then, work out how elections work with term limits and clear rules.

2022-12-15 08:54 UTC, patrickzib approved these changes

2022-12-16 00:05 UTC, closed without merging