[DOC] Fix lag doc examples
sktime/sktime pull request #3960
Opened 2022-12-20 11:37 UTC by aiwalter

Fixes `Examples` section in `Lag` transformer. It was wrongly rendered on website.

2022-12-29 12:39 UTC, lmmentel approved these changes

2022-12-29 15:09 UTC, fkiraly commented on sktime/transformations/series/lag.py
> +        pipeline step does not accept NA.cTo deal with the NAs,
typo

2022-12-29 15:09 UTC, fkiraly requested changes
makes sense, kindly fix the typo accidentally introduced

2023-01-30 21:12 UTC, fkiraly commented on sktime/transformations/series/lag.py
> +        pipeline step does not accept NA.cTo deal with the NAs,
fixed it myself now

2023-01-30 21:28 UTC, merged