[MNT] isolate `mlflow` and AWS dep set
sktime/sktime pull request #3975
Opened 2022-12-21 19:14 UTC by fkiraly

This PR cleans up the dependency set from https://github.com/sktime/sktime/pull/3912 - `mlflow` and AWS dependencies are moved to a separate dependency set `mlflow`.

The CI for `mlflow` is also separated and isolated from the remaining tests, ensuring that the remaining tests do not need to install a large python env.

2022-12-21 19:20 UTC, aiwalter requested changes
I think only mlflow is needed to run the code. Others are test related?

2022-12-21 19:20 UTC, fkiraly commented
FYI @benjaminbluhm

2022-12-21 19:21 UTC, fkiraly commented
>I think only mlflow is needed to run the code. Others are test related?

If you want to use mlflow on AWS, I think you need those.
In the CI it is treated as being a test related dependency set - there is no doc that encourages the user to install `sktime[mlflow]`

2022-12-21 19:23 UTC, aiwalter commented
Well we dont need to provide installs for particular platform. Also AWS will have this installed by default then.

2022-12-21 19:26 UTC, fkiraly commented
>Well we dont need to provide installs for particular platform. Also AWS will have this installed by default then.

Can you please phrase your comments as a change request?

2022-12-21 19:36 UTC, aiwalter commented
I think this PR is not required, so change reqeust would be to close it?😊

2022-12-21 19:38 UTC, fkiraly commented
can you please provide an explanation why it is not required?
This is a supplement to #3912.

2022-12-21 19:39 UTC, fkiraly commented
If you block this, I will revert the `mlflow` PR, otherwise we overload the `all_extras` environment with large packages.

2022-12-21 19:44 UTC, aiwalter commented
There was only added mlflow

2022-12-22 00:57 UTC, fkiraly commented
I'm interpreting this as an unblock, then.

2022-12-22 00:57 UTC, merged