[DOC] - Updated pull request template to add new tests
sktime/sktime pull request #4081
Opened 2023-01-07 15:49 UTC by Aarthy153

#### Description
Updated the file `PULL_REQUEST_TEMPLATE.md` by adding a separate section for the contributors to add their additional tests. 

#### Issue reference
#4066 

#### Screenshot of the fix

2023-01-09 14:49 UTC, Aarthy153 commented
@miraep8 @fkiraly @GuzalBulatova requesting you to review this!

2023-01-09 21:44 UTC, miraep8 approved these changes
Looks good to me! Thanks for making this change!

2023-01-10 10:33 UTC, fkiraly requested changes
Looks good to me too!
Unfortunately linting (i.e., code formatting) is failing, here is the guidance how to ensure that code is formatted correctly:
https://www.sktime.org/en/latest/developer_guide/coding_standards.html
Let us know if you need help with that.

2023-01-10 10:34 UTC, fkiraly commented on .github/PULL_REQUEST_TEMPLATE.md
> +#### Did you add any tests rather than the exisiting ones?
maybe we could shorten this, e.g., "Did you add any tests for the change?"

2023-01-10 14:56 UTC, closed without merging