[ENH] Add HPFilter Transformer
sktime/sktime pull request #4342
Opened 2023-03-16 04:19 UTC by ken-maeda

Reference Issues/PRs
Reference https://github.com/sktime/sktime/issues/4089

What does this implement/fix? Explain your changes.

Built HPFilter Transformer using statsmodels time series filters.
Added a separate test "test_hpfilter" to test transformer against statsmodels

Almost similar to #4127
Difference of bkfilter and hpfilter
- input array support only 1d array
- output style( outputs in statsmodels are cycle and trend )

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

2023-03-16 14:13 UTC, fkiraly requested changes
Great, thanks for your contribution!

Some change requests:

* kindly don't copy-paste the code from `statsmodels` but import it. That way, improvements and bugfixes directly propagate to sktime.
* The docstring should give clear credit, i.e., this is a direct interface to `statsmodels.etc.etc`
* `x` is not a parameter to the constructor, kindly fix
* kindly ensure your code passes code quality checks: https://www.sktime.net/en/latest/developer_guide/coding_standards.html#coding-standards

2023-03-16 15:02 UTC, ken-maeda commented
@fkiraly I appriciate your feedback. I have a question to clarify.

> kindly don't copy-paste the code from statsmodels but import it. That way, improvements and bugfixes directly propagate to sktime. Generally, we should avoid "forking" code (by copy-paste etc).

It means `HPFilter.transform_ ` is just like

```
def _transform(self, X, y=None):
  import statsmodels.api as sm
  
  cycle = sm.tsa.filters.hpfilter(X, self.lamb)[0]
  return cycle 
```
I thought I was refering BKfilter code to Hpfilter. BKfilter in sktime is like statsmodels code.

I maybe missed something about this enhancement. (I'm sorry for causing you trouble)

About other problem, I'm clear.

2023-03-16 17:53 UTC, fkiraly commented
@ken-maeda, you are right, `BKFilter` accidentally does the same thing, copying.
I've fixed it in this PR: https://github.com/sktime/sktime/pull/4346

Sorry for pointing you to a buggy template.

> It means HPFilter.transform_ is just like

Indeed! It is quite simple - one might ever cover it with a single adapter class and then expose the filters as special cases (descendants).

2023-03-23 22:35 UTC, fkiraly commented
small linting failures, you can have a look in the GitHub GUI if you click on "details" next to the failure

2023-03-25 01:03 UTC, fkiraly commented on sktime/transformations/series/hpfilter.py
> +__author__ = ["klam-data", "pyyim", "mgorlin", "ken_maeda"]
I think the author should be just you?

2023-03-25 01:04 UTC, fkiraly commented on sktime/transformations/series/hpfilter.py
> +        params = {"lamb": 1600}
there should always be at least two parameter sets.

I would go with an empty dict (the default) and this one.

2023-03-25 01:04 UTC, fkiraly commented on sktime/transformations/tests/test_hpfilter.py
> +__author__ = ["klam-data", "pyyim", "ken-maeda"]
this should be just you

2023-03-25 01:05 UTC, fkiraly commented on docs/source/api_reference/transformations.rst
> +.. currentmodule:: sktime.transformations.series.hpfilter
actually, could you kindly move the `Filter` to the top?
Things should roughly be ordered by how common they are, I think `Filter` (generic band pass) is the most common filter people might be looking for. The others are more finance/econ specific afaik.

2023-03-25 01:06 UTC, fkiraly requested changes
left some small comments above.

The only ones blocking are the linting failure and the author lines.

2023-03-25 15:46 UTC, ken-maeda commented
@fkiraly I think it should be fixed now.

2023-03-25 15:59 UTC, fkiraly commented on sktime/transformations/series/hpfilter.py
> +    x : array_like
`x` is not a parameter to the estimator, kindly remove this one

2023-03-25 16:00 UTC, fkiraly requested changes
Looks great!

Two things:
* the docstring which has a superfluous `x` argument - probably a copy-paste accident.
* the example in the docstring does not work (this is tested), since you are using `sm`, instead import `statsmodels`. Also, kindly use doctest skip in the docstring example to isolate the soft dependency.

2023-03-26 20:53 UTC, fkiraly approved these changes
Great, thanks a lot!

2023-03-26 20:55 UTC, merged