Devdoc
sktime/sktime pull request #4572
Opened 2023-05-11 12:59 UTC by wasup-yash

#### Reference Issues/PRs
Closes #4558

#### What does this implement/fix? Explain your changes.
Added DocStrings for the `[SimpleRNNClassifier]`(https://github.com/sktime/sktime/blob/main/sktime/classification/deep_learning/rnn.py#L20)

2023-05-11 17:08 UTC, yarnabrina commented
@fkiraly just a quick question: why do most of `deep_learning` directory codes have a different docustring style from rest? These extra spaces before `:` are not really common in other `sktime` modules or even in `numpydoc` etc.

Not that it's objectively bad or anything, just asking because of inconsistent (if it matters for docstrings) style from most of other modules.

2023-05-11 19:35 UTC, fkiraly commented
> @fkiraly just a quick question: why do most of `deep_learning` directory codes have a different docustring style from rest? These extra spaces before `:` are not really common in other `sktime` modules or even in `numpydoc` etc.

Because it has been without maintenance for a period of time - most deep learning estimators lived originally in `sktime-dl`, which got abandoned as its maintainers did not keep up with the professionalisation of the software architecture in the main package (which also included better docstrings as a side effect).

As content has been migrated to `sktime`, the interfaces have been updated, but the docstrings often still are in the old style.

2023-05-17 13:37 UTC, fkiraly commented on sktime/classification/deep_learning/rnn.py
> +    should inherited fields be listed here?
what do you mean by that? Like `random_state`?

Yes, all args of `__init__`.

2023-05-17 13:37 UTC, fkiraly requested changes
Thanks, this looks great!

Could you kindly remove the "should inherited fields" question from the docstring? Sth like this is better asked in the PR thread.

2023-05-17 13:47 UTC, wasup-yash commented
> 

> Thanks, this looks great!
> 
> Could you kindly remove the "should inherited fields" question from the docstring? Sth like this is better asked in the PR thread.

ok I am gonna remove it, thanks for the review

2023-05-17 14:02 UTC, fkiraly requested changes
now waitasec, I just noticed - and apologies for not noticing earlier - the defaults in the docstring don't actually agree with those in the `__init__`!

Can you kindly fix that? Also, where the default is `None` (e.g., ,`optimizer`), you should check what it is set to internally, e.g., is it `Adam`?

2023-05-17 14:27 UTC, wasup-yash commented
> now waitasec, I just noticed - and apologies for not noticing earlier - the defaults in the docstring don't actually agree with those in the `__init__`!
> 
> Can you kindly fix that? Also, where the default is `None` (e.g., ,`optimizer`), you should check what it is set to internally, e.g., is it `Adam`?

oh, sorry for not noticing it from my side too, I'll work on it and update it for the review.

2023-05-23 07:51 UTC, fkiraly approved these changes
Fixed outstanding items for the release

2023-05-23 07:52 UTC, merged

2023-05-23 09:01 UTC, wasup-yash commented
> Fixed outstanding items for the release

thanks a lot @fkiraly for the fixes, I was indulged in uni exams and thought gonna work on it but you already fixed the docs, Really appreciate it.