changing Union[int | float] to float as per issue #4379
sktime/sktime pull request #4575
Opened 2023-05-11 17:03 UTC by mdsaad2305

#### Reference Issues/PRs
issue #4379 

#### What does this implement/fix? Explain your changes.
This is my first contribution.
changing Union[int | float] to just float

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2023-05-11 19:33 UTC, fkiraly requested changes
Thanks!

There are a lot of other occurrences of `Union[int, float]`, so it would be great if you could also take care of those - simply use vs code or pycharm search all files functionality.

2023-05-11 19:40 UTC, mdsaad2305 commented
Will make the necessary changes

2023-05-11 20:42 UTC, mdsaad2305 commented
I think these are the only occurrences of `Union[float, int]` and `Union[int, float]`. Furthermore, I recall the flake8 test failing during pre-commit due to the import statements, so I removed them

2023-05-12 01:30 UTC, fkiraly commented
> I think these are the only occurrences of `Union[float, int]` and `Union[int, float]`.

Yes, I think you got all of them, thanks!

2023-05-12 01:31 UTC, fkiraly approved these changes
Thank you!

2023-05-12 01:33 UTC, merged