[MNT] update pre commit hook versioons and corresponding changes
sktime/sktime pull request #4680
Opened 2023-06-06 04:21 UTC by yarnabrina

Closes #4676.

What this PR does:

1. Update hook versions.
2. Apply code formatting changes identified by `black`. (affected ~140 files)
3. Apply docstring length/style changes identified by `flake8`+`pydocstyle`. (affected ~180 files)

Notes for reviewers:

* For the 3rd point above, used `docformatter` locally to automate few docstring changes, and these are part of d736b6624d5e6254da4a7888d491eb157dcb0ccf.
* In few places where it was unable to solve the issues (mostly `D205` and `D400`), used my own judgement to modify docstrings slightly to avoid lint failures. These possibly biased changes are part of ae526adfb2eef63970803bb51d5babe0245438ec, and should be reviewed carefully.

2023-06-10 17:03 UTC, fkiraly commented on sktime/_contrib/distance_based/_proximity_forest.py
> +                instances that match that label
funny change

2023-06-10 17:03 UTC, fkiraly commented on sktime/_contrib/distance_based/_proximity_forest.py
> +        :return: 2d numpy array of distances from each instance to each         exemplar
funny change

2023-06-10 17:03 UTC, fkiraly commented on sktime/_contrib/distance_based/_proximity_forest.py
> +                [n_instances,[n_tree_estimators,labels]] which contains an array of
funny change

2023-06-10 17:05 UTC, fkiraly requested changes
Thanks!

* the changes touch a lot of files, although it is mainly linting
* I noticed a few funny changes, not sure what is at cause of them, but it looks in a few instances the formatting gets worse, not better like in the rest - what is happening there?
* also, quick question: is this introducing anything that would break for the user? I guess not, so it can go with 0.19.2, but just checking your understanding.

2023-06-10 19:50 UTC, yarnabrina commented
> I noticed a few funny changes, not sure what is at cause of them, but it looks in a few instances the formatting gets worse, not better like in the rest - what is happening there?

The three changes you pointed out are all automated changes, not by myself. I am not very familiar with `sphinx` style docstrings, but I believe that the standard `docformatter` is following is if the description length exceeds configured line length, which is the same as that of `black`, it splits into next line and adds an indentation. The GitHub diff looks weird, but seeing the actual file contents in VS Code makes it clearer.

> is this introducing anything that would break for the user?

I've made no code changes myself. It should be good to go. May be not in this PR, but in a different PR we can consider adding a workflow rule of auto-updating hooks in a schedule to avoid such big PR's in future.

---

I merged `main` and ran the hooks once again. Few more files got changed this time, but mostly whitespace related changes in docstrings. Also replaced curly/smart quotes with straight quotes using `texthooks`. Please take a look.

2023-06-16 20:35 UTC, fkiraly approved these changes
Happy with this.

2023-06-17 13:22 UTC, merged

2023-06-17 13:23 UTC, fkiraly commented
(the docstring fixes look fine)