Update .all-contributorsrc
sktime/sktime pull request #5180
Opened 2023-08-29 18:32 UTC by alexfilothodoros

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2023-08-29 19:41 UTC, fkiraly commented on .all-contributorsrc
>  }
please ensure you follow the pattern of brackets & commas

2023-08-29 19:43 UTC, fkiraly requested changes
formatting issue, see above.

Otherwise fine once https://github.com/sktime/sktime/pull/5169 is merged.

Also, I think the badge should be "maintenance", not "example", since you didn't add content, but changed content so the tests and notebooks run faster.

2023-09-03 10:09 UTC, fkiraly approved these changes
fixed the formatting to ensure this is included in the automatic contributor update

2023-09-03 15:33 UTC, alexfilothodoros commented
> fixed the formatting to ensure this is included in the automatic contributor update

Thanks for that :)

2023-09-03 20:03 UTC, merged