[ENH] FourierFeatures more periodicity options
sktime/sktime pull request #5513
Opened 2023-11-01 13:13 UTC by Ram0nB

#### Reference Issues/PRs
Fixes #5512

#### What does this implement/fix? Explain your changes.

See Issue #5512 for a description of the problem and the solution implemented in this PR.

For periodicity defined as a pandas period alias, a private method is added that takes the period alias and a datetime index, and returns per datetime the fraction of the period that has passed in the interval [0, 1).

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
All changed files :)

#### Did you add any tests for the change?
No

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

2023-11-01 19:26 UTC, fkiraly commented on sktime/transformations/series/fourier.py
> +    "cos_12_1", "sin_12_1", "cos_12_2", "sin_12_2", "cos_Y_1", "sin_Y_1"
something isn't quite right here. Is this the paired product or the cross-product?

If we pair 12, Y and 2,1, then we get (12, 2) and (Y, 1), so should we not get `"cos_12_2", "sin_12_2", "cos_Y_1", "sin_Y_1"` only?

Whereas if we cross-product them, we get (12, 2), (12, 1), (Y, 2), (Y, 1), so should we not get `"cos_12_2", "sin_12_2", "cos_12_1", "sin_12_1", "cos_Y_2", "sin_Y_2", "cos_Y_1", "sin_Y_1"`, in this order?

Neither plausible options seems to give the claimed columns.

2023-11-01 19:27 UTC, fkiraly requested changes
Nice!

Blocking, perhaps just an explanation: which columns exactly does this produce? The issue already seems to have been with the estimator as is, but we still should fix the documentation to agree with the actual.

Non-blocking: there are now multiple options for `sp_list`, I would translate the dense paragraph to a bullet point list of options.

2023-11-03 11:04 UTC, Ram0nB commented
> Nice!
> 
> Blocking, perhaps just an explanation: which columns exactly does this produce? The issue already seems to have been with the estimator as is, but we still should fix the documentation to agree with the actual.
> 
> Non-blocking: there are now multiple options for `sp_list`, I would translate the dense paragraph to a bullet point list of options.

I agree with both points: I just updated the docstring. Let me know if you think this is clear enough for the user :smiley:

2023-11-03 11:12 UTC, fkiraly requested changes
Ah, it's paired and "up to the number".

Although the math is a bit discrepant, the math claims that the indexing is 0-based, but the naming is 1-based.

Can you kindly check?

2023-11-05 15:54 UTC, fkiraly commented on sktime/transformations/series/fourier.py
> +    "cos_12_1", "sin_12_1", "cos_12_2", "sin_12_2", "cos_Y_1", "sin_Y_1"
thanks for the explainer, clear now.

2023-11-05 15:55 UTC, fkiraly approved these changes
Updated the docstring, so it's ready for the release.

2023-11-05 15:57 UTC, merged