[DIAG] Diagnose Sporadic Test Errors in `ExponentialSmoothing`
sktime/sktime pull request #5516
Opened 2023-11-02 12:59 UTC by achieveordie

This is a diagnosis PR to check the issue first encountered in #5026.

Due to this bug, `ExponentialSmoothing`'s `.predict()` returns `NaN` sporadically, causing subsequent operations to fail since they expect finite values.

2023-11-02 14:56 UTC, fkiraly commented
one question is also, does this happen locally as well as remote, or only remote?

Locally, you can run a loop of 100 `check_estimator`-s with the offending test and see how often it happens.

2023-11-02 15:02 UTC, achieveordie commented
I tried what you're suggesting with only 10 iterations but found no errors. I'll try increasing it.

2023-11-02 15:05 UTC, fkiraly commented
you can get more iterations in if you select the specific test

2023-11-02 16:39 UTC, achieveordie commented
Here are my findings:
- The failing estimator is `ExponentialSmoothing` and the failing method is `TestAllForecasters::test_score()` (from the runners in the PR).
- Every single call yields 12 tests in total(different param combinations etc), here's an example of one of those:
``` python
{'test_score[ExponentialSmoothing-0-y:1cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-0-y:1cols-fh=[2 5]]': 'PASSED', 'test_score[ExponentialSmoothing-0-y:2cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-0-y:2cols-fh=[2 5]]': 'PASSED', 'test_score[ExponentialSmoothing-1-y:1cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-1-y:1cols-fh=[2 5]]': 'PASSED', 'test_score[ExponentialSmoothing-1-y:2cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-1-y:2cols-fh=[2 5]]': 'PASSED', 'test_score[ExponentialSmoothing-2-y:1cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-2-y:1cols-fh=[2 5]]': 'PASSED', 'test_score[ExponentialSmoothing-2-y:2cols-fh=1]': 'PASSED', 'test_score[ExponentialSmoothing-2-y:2cols-fh=[2 5]]': 'PASSED'}
```
- I ran the test for 1000 iterations getting 12000 total test runs, out of which 46 failed. Curiously, these failures were coming from only two combinations:
``` python
{'test_score[ExponentialSmoothing-2-y:1cols-fh=[2 5]]': 14, 'test_score[ExponentialSmoothing-2-y:2cols-fh=[2 5]]': 32}
```
(Note: ExponentialSmoothing-2 is the one that contains `use_boxcox=True` if the order of test params is considered the same order)

If my hypothesis is correct, this number should go down to zero after `use_boxcox=False` in test params. I'll soon update this comment after running the diagnosis script with new param set (will also add the script here for reference).

2023-11-02 18:37 UTC, yarnabrina reviewed
I am not sure if it's a bugfix. It uses a test case that passes, but does it resolve the bug that occasionally fails the other test case(s)?

2023-11-02 18:48 UTC, achieveordie commented
> I am not sure if it's a bugfix. It uses a test case that passes, but does it resolve the bug that occasionally fails the other test case(s)?

This fixes the CI errors that were prominent across different PRs by "fixing" the test params. The actual source of error is considered to be numerical instability arising from statsmodel, and according to the comments, is by nature of this model (and perhaps their implementation).

So any other solution, if any, lies beyond the scope of sktime.

2023-11-02 21:32 UTC, fkiraly requested changes
But that's not a "fix", in the sense that it just reduces test coverage away from the failure case?

A "fix" would be sth, e.g., that does not reduce test coverage, but does sth to ensure we are interface compliant even in the sporadic failure case, such as filling zero, or restarting the fit, etc.

2023-11-03 19:14 UTC, achieveordie commented
Hmm, I'm not sure if I agree with monkey-patching it. I agree with you and @yarnabrina (I think this is what he was implying too, I just misunderstood his statement) that this reduces the test coverage. Perhaps restarting the fit function should be a good alternative.

2023-11-04 08:50 UTC, fkiraly commented
That wouldnt be a monkey-patch, would it? Simply a fallback patch in case it would have failed.

2024-01-20 21:20 UTC, merged