[DO] Use simple table ReST syntax for tables in API docs
sktime/sktime pull request #5595
Opened 2023-12-02 15:47 UTC by rahulporuri

Similar to #5564, this PR updates the (mostly broken) ReST table syntax in API documentation.

#### Reference Issues/PRs
N/A

#### What does this implement/fix? Explain your changes.

Update docstrings to use the [ReST simple tables syntax](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#simple-tables)

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

Confirm that the API docs look correct from the docs built on this branch

#### Did you add any tests for the change?

N/A

#### Any other comments?
No

#### PR checklist

##### For all contributions
- [ ] ~I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)~
- [ ] ~Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).~
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] ~I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.~
- [ ] ~I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.~
- [ ] ~If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).~

2023-12-02 19:25 UTC, fkiraly commented
this is how it looks like - does not seem quite right:

![image](https://github.com/sktime/sktime/assets/7985502/598cef86-fadd-4c55-89af-c56d9ad0ddcc)

Should it not be a table?

I thought this was fine:

```

        .. list-table::
            :widths: 35 35 40
            :header-rows: 2
            * -
              - `transform`
              -
            * - `X`
              - `-output`
              - type of return
            * - `Series`
              - `Primitives`
              - `pd.DataFrame` (1-row)
            * - `Panel`
              - `Primitives`
              - `pd.DataFrame`
            * - `Series`
              - `Series`
              - `Series`
            * - `Panel`
              - `Series`
              - `Panel`
            * - `Series`
              - `Panel`
              - `Panel`
```

(it results in an rst table)

2023-12-07 15:39 UTC, rahulporuri commented
> (it results in an rst table)

@fkiraly it does result in a ReST table but that ReST table is only easily readable in the built docs. The code itself isn't as readable, in my humble opinion.

But if this isn't the look you're all going for, i'm okay with using the `list-table` style ReST table.

2023-12-07 16:17 UTC, yarnabrina commented on docs/source/estimator_overview_table.md
Can you please explain addition of this new file? What are you trying to add?

Also, how is this going to interact with lines 373-374 in `conf.py` file?

https://github.com/sktime/sktime/blob/df21a0c0275ebf28deb30efac5d469c9f0d178e3/docs/source/conf.py#L373-L374

2023-12-10 18:28 UTC, fkiraly requested changes
>@fkiraly it does result in a ReST table but that ReST table is only easily readable in the built docs. The code itself isn't as readable, in my humble opinion.

I know, but the rst docs also do not look that great.

How about this compromise:

* in public methods, we use rest syntax
* in private methods (which is what someone looking at estimator code sees), we use sth that looks like a table?

Or, we repeat the table as a comment?

2024-10-08 07:38 UTC, closed without merging