[Bug] Modified the default loss function to `CNNClassifier`
sktime/sktime pull request #5852
Opened 2024-01-28 05:32 UTC by Vasudeva-bit

#### Reference Issues/PRs

PR of sktime-dl [there](https://github.com/sktime/sktime-dl/pull/128) is migrated here.

#### What does this implement/fix? Explain your changes.

I have modified the default loss function to `CNNClassifier`, based on the conversations [here](https://github.com/sktime/sktime-dl/pull/128), from `mean_squared_error` to `categorical_crossentropy`.

#### Does your contribution introduce a new dependency? If yes, which one?

No.
#### What should a reviewer concentrate their feedback on?

If it is any better to approach this fix similar to handling `optimizer` parameter in the same classifier [here](https://github.com/sktime/sktime/blob/0efea1fcf240fad8f7775a41c6627781707add1f/sktime/classification/deep_learning/cnn.py#L151), I shall modify accordingly.

#### Did you add any tests for the change?

No

2024-01-28 05:39 UTC, achieveordie submitted a review, later dismissed
LGTM, thanks!

2024-01-28 05:44 UTC, achieveordie commented
Regarding your question, I don't believe we need any if statements since we already have a default.

What would be great though is to checkout whether other dl classifiers can be improved in the same manner.

2024-01-28 05:46 UTC, achieveordie commented
Ah oh, please update the docstring as well :)

2024-01-28 15:56 UTC, fkiraly commented
hm, question from my side, FYI @yarnabrina, @benHeid - does this need deprecation? Behaviour is changed, but MSE is a unusual choice for classification.

2024-01-29 14:44 UTC, yarnabrina commented
> does this need deprecation?

In my opinion, yes. But considering unusual choice of loss, we can possibly do a shorter deprecation (1 minor) instead 2 as usual.

2024-01-30 05:35 UTC, achieveordie commented
fwiw, I think it most probably was a mistake when copy-pasting it from `CNNRegressor` hence it does not warrant any deprecation.

2024-01-31 16:15 UTC, Vasudeva-bit commented
> Also, is "sigmoid" a good choice for `categorical_crossentropy`, or `softmax` is a better choice?

I think `softmax` should be the default choice as it works better in case of multi-class classification and works just like `sigmoid` in case of binary classification. However, `sigmoid` is more appropriate choice in case of multi-label classification. Sorry, Shall I go ahead and change the default choice for activation?

2024-01-31 16:25 UTC, yarnabrina commented
> I think softmax should be the default choice as it works better in case of multi-class classification and works just like sigmoid in case of binary classification.

Yes, my comment from this exact point of view. Multi-class is more common than multi-label, so I'll suggest to change the default loss. May be @achieveordie / @fkiraly  can share their opinions too?

2024-02-04 05:42 UTC, yarnabrina requested changes
LGTM otherwise, except for possible deprecation for at least one minor cycle.

2024-02-04 05:42 UTC, yarnabrina commented on sktime/classification/deep_learning/cnn.py
>      activation      : string or a tf callable, default="sigmoid"
```suggestion
    activation      : string or a tf callable, default="softmax"
```

This should also be changed now.

2024-02-20 18:02 UTC, yarnabrina approved these changes

2024-02-20 18:07 UTC, merged