Add `NeuralForecastLSTM` model
sktime/sktime pull request #6047
Opened 2024-03-02 06:48 UTC by pranavvp16

Sktime already has an adapter for `neuralforecast` which only implements `RNN` model. RNN's suffer from problems like gradient vanishing while training, So I it's good to have LSTM model implemented that works better than RNN for time-series forecasting. 

Here is a demo of LSTM implemented in sktime using neuralforecast [notebook](https://colab.research.google.com/drive/1R9z5HS4uRpzVuVYKMHoB-q3-osWgHyD_?usp=sharing)

2024-03-02 07:44 UTC, yarnabrina requested changes
Thanks for your contribution. I made some comments, please take a look. You also need to add a reference in `docs/source/api_reference/forecasting.rst` for this to appear on the public documentation.

Also there are few FYI:

- I created https://github.com/Nixtla/neuralforecast/issues/910 and if they decide to add a new argument, this needs to be added.
- @geetu040 is working on https://github.com/sktime/sktime/pull/6039 and if that is merged, this needs to be updated as well.
- I added RNN first just to test the adapter, as it was the first model on their site. There is no ther reasoning. You are very much welcome to add interfaces to all the other models, especially the `Auto*` ones which tend to be more popular.

2024-03-02 07:44 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +    """NeuralForecast RNN model.
Thanks for spotting this.

2024-03-02 07:44 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +
Can we keep it at end of file please?

2024-03-02 07:44 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +    frequency of the data, see available frequencies [4]_ from ``pandas``
```suggestion
        frequency of the data, see available frequencies [4]_ from ``pandas``
```

This should be indented.

2024-03-02 07:44 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +    - 'boxcox'
Same as above, should be indented.

2024-03-02 07:44 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
I think we should update this in a more general way, if most (at least non-auto) models from `neuralforecast` have similar format. Instead of copying same tests, can you parametrise them over different model classes please?

2024-03-02 17:12 UTC, pranavvp16 commented
@yarnabrina I have parameterized the tests and also fixed the indentation faults. Talking about the `auto` frequency detection , let's merge this for now, I'll update it as soon as #6039 is merged. Also I'll keep and eye on the issue you mentioned regarding the `encoder_activation` function, and make changes once it is fixed.

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +    Interface to ``neuralforecast.models.LSMT`` [1]_
```suggestion
    Interface to ``neuralforecast.models.LSTM`` [1]_
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +    multilayer LSTM encoder and an MLP decoder
```suggestion
    multilayer LSTM encoder and an MLP decoder.
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +        # "authors": ["pranavvp16"],
```suggestion
        "authors": ["pranavvp16"],
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/neuralforecast.py
> +        # "maintainers": ["yarnabrina", "pranavvp16"],
```suggestion
        "maintainers": ["pranavvp16"],
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +"""Tests for NeuralForecastRNN, NeuralForecastLSTM."""
```suggestion
"""Tests for interfacing estimators from neuralforecast."""
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +    """Test NeuralForecast with single endogenous without exogenous."""
```suggestion
    """Test with single endogenous without exogenous."""
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +    """Test NeuralForecast with single endogenous with exogenous."""
```suggestion
    """Test with single endogenous with exogenous."""
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +    """Test NeuralForecast with multiple endogenous without exogenous."""
```suggestion
    """Test with multiple endogenous without exogenous."""
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +    """Test NeuralForecast models with multiple endogenous without exogenous."""
```suggestion
    """Test with multiple endogenous without exogenous."""
```

2024-03-03 04:13 UTC, yarnabrina commented on sktime/forecasting/tests/test_neuralforecast.py
> +    """Check NeuralForecast fail when multiple prediction columns are used."""
```suggestion
    """Check fail when multiple prediction columns are used."""
```

2024-03-03 04:19 UTC, yarnabrina approved these changes
All looks good to me for now. I added some minor text changes, hopefully that's okay with you.

In future, we need to plan how to handle testing for classes with different expectations. It's likely that group of algorithms may have similar behaviour and we can parametrise instead of code duplication, but not over all of them.

2024-03-04 03:26 UTC, merged