[ENH] Migrate DL networks from sktime-dl: TLENET
sktime/sktime pull request #6056
Opened 2024-03-04 06:29 UTC by nilesh05apr

#### Reference Issues/PRs
Part of https://github.com/sktime/sktime/issues/3351. See also https://github.com/sktime/sktime/pull/3365

#### What does this implement/fix? Explain your changes.
Migrated detworks for TLENET from sktime_dl to sktime deep_learning

#### What should a reviewer concentrate their feedback on?
Code style and comments are correct about the algorithms

#### Did you add any tests for the change?
None yet

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-03-04 09:43 UTC, fkiraly commented
A lot of code formatting failures, see here how to set code formatting checks locally:
https://www.sktime.net/en/stable/developer_guide/coding_standards.html

2024-03-06 16:01 UTC, fkiraly commented
Sure!

There seem to be two issues:

* code formatting failures, see here how to address these: https://www.sktime.net/en/stable/developer_guide/coding_standards.html
* probably some syntax error in addition, since docs fail to compile. Try to run your code, using simple exapmles or via `utils.check_estimator`.

2024-03-11 14:42 UTC, nilesh05apr commented
@fkiraly I have checked the pre-commit it works fine with no errors, what shall I do?

2024-03-12 00:50 UTC, fkiraly commented
something must be wrong with your precommit setup then.

As an alternative, you can check "details" here:
![image](https://github.com/sktime/sktime/assets/7985502/48b3a61f-877a-4210-852e-d66f4753a9c8)

and you could ask in the dev-chat, or in one of the meet-ups, if you can't get the precommit to work

2024-03-12 04:38 UTC, nilesh05apr commented
@fkiraly Thanks, I understood what was the problem, there was a typo in the name of the regressor, and some line lengths were more than 80 characters.
I fixed those minor issues, one more thing, I wanted to add the Tlenet classifier also in this same pr, so please wait for it before merging.

2024-03-12 13:57 UTC, fkiraly requested changes
Adddition of `TleNetClassifier` and `TleNetRegressor` look good.

Though, could you explain why we are changing the name of `LSTMFCNNetwork`?

This does not seem to be a necessary change, and since it's been released previously, we cannot change the name without deprecation.

2024-03-13 04:05 UTC, nilesh05apr commented
@fkiraly about lstmfcn, it is my mistake. The IDE seems to auto-correct the name. I will change it back to normal.
but can you please check why mlfow tests are failing?

2024-03-14 00:13 UTC, fkiraly commented
> but can you please check why mlfow tests are failing?

That's unrelated, it's caused by a recent update, see #6094

2024-03-18 19:48 UTC, nilesh05apr commented
@fkiraly how to fix this issue?

2024-03-18 21:51 UTC, fkiraly commented on sktime/tests/_config.py
> +    "TleNetRegressor",
we should not add exceptions here!

2024-03-18 21:52 UTC, fkiraly requested changes
The failures coming from other issues do not need to be resolved in this PR - recent updates to `main` should have resolved them.

Some outstanding issues:

* the new estimators should not be added to the test exception list - how would we know that they work?
* can you also please add the estimators to the respective API references?

2024-03-22 11:59 UTC, fkiraly requested changes
Thanks! The failures look genuine, e.g.,

```
Error in TleNetRegressor.get_test_params, return must be valid param dict for class,
or list thereof, but attempted construction raised a exception.
Problematic parameter set: {'n_epochs': 25, 'batch_size': 4, 'warping_ratio': [0.5, 1, 2], 'slice_ratio': 0.1}.
Exception raised: __init__() got an unexpected keyword argument 'n_epochs'
```

2025-09-30 17:01 UTC, closed without merging