[BUG] Change file ending
sktime/sktime pull request #6098
Opened 2024-03-09 19:12 UTC by benHeid

#### Reference Issues/PRs
Fixes #6094 

#### What does this implement/fix? Explain your changes.
It uses the proposed save format of tensorflow. To be downward compatible, I introduced an if-else statement to select the save functionality. Should we warn the user and deprecate the old 

#### What should a reviewer concentrate their feedback on?
Is the deprecation cycle appropriate? 

#### Did you add any tests for the change?

No

2024-03-09 19:58 UTC, fkiraly requested changes
Hm, I see.

The issue is, the general `save` contract assumes that the function loads and writes to any file name, so forcing a file ending would violate that.

Would a solution that satisfies the contract not rather be this:

* save to a file with the ending
* rename the file

Or similar?

Further, the specification - and docstring - says the file should be a `zip`. I am a bit confused why the ending is required in the serialized file, rather than, say, in a file that is contained in the `zip`.

2024-03-09 20:20 UTC, benHeid commented
> Hm, I see.
> 
> The issue is, the general `save` contract assumes that the function loads and writes to any file name, so forcing a file ending would violate that.
> 
> Would a solution that satisfies the contract not rather be this:
> 
> * save to a file with the ending
> * rename the file
> 
> Or similar?

I suppose this would be possible. However, I do not really like to do that, because I think it is very confusing, since file endings normally contains information on how to interpret a file and this would not be possible. 
 
> Further, the specification - and docstring - says the file should be a `zip`. I am a bit confused why the ending is required in the serialized file, rather than, say, in a file that is contained in the `zip`.

Currently, it can be a zip file if the version is lower than 2.16.0 and legacy_save=True. But I can change the docstrings..

2024-03-09 20:27 UTC, fkiraly commented
> because I think it is very confusing, since file endings normally contains information on how to interpret a file and this would not be possible.

I think it would be more confusing to have different file endings depending on estimator - the whole idea is to abstract that away for the user, and it's always `zip`.

This has unfortunately not been written up properly, I cannot find it in the file specifications folder. @achieveordie, do you remember where the specification for the model serialization format went?

2024-03-09 20:30 UTC, fkiraly commented
Found it - this should be moved to file specifications
https://github.com/sktime/enhancement-proposals/blob/main/steps/20_saveload/step.md

2024-03-09 20:37 UTC, fkiraly commented
FYI @blazingbhavneek, @AurumnPegasus, in case you are still active.

2024-03-09 20:39 UTC, benHeid commented
> I think it would be more confusing to have different file endings depending on estimator - the whole idea is to abstract that away for the user, and it's always `zip`.


Thus a solution then could be save it as .keras and putting this file into a zip?

2024-03-09 20:55 UTC, fkiraly commented
> Thus a solution then could be save it as .keras and putting this file into a zip?

Yes - I'm slightly surprised that it wasn't already in a `zip` file, seems like an oversight related to not having written up the specs properly.

2024-03-09 21:43 UTC, benHeid commented
Ok the remaining error seems to be caused by the in memory serialization. Unfortunately, I have no good idea how to solve it... Since `save` is only accepting str or Path objects and no files anymore as in the current code:

```python
if self.model_ is not None:
    with h5py.File(
        "disk_less", "w", driver="core", backing_store=False
    ) as h5file:
        self.model_.save(h5file)
        h5file.flush()
        in_memory_model = h5file.id.get_file_image()
```

2024-03-11 18:46 UTC, benHeid commented on sktime/classification/tests/test_base.py
> +        assert full_dummy.optimizer.variables == deserialized_full.optimizer.variables
Probably yes. However, this is part of the tests and the tests are always executed with the newest packages. Thus, I haven't added that check.

2024-03-11 21:01 UTC, fkiraly submitted a review, later dismissed
Approved under the assumption that you tested it.

What I'm a bit surprised about is that there's no `legacy_save` method distinction in the loader.

If that is so, then is the `legacy_save` parameter in `save` unnecessary? Or will it load only files saved in the new way now? If that does not "match", then this comment is blocking (as it would mean users cannot use `legacy_save` for loading, saving with that param becomes "write-only").

2024-03-11 21:07 UTC, benHeid commented
> Approved under the assumption that you tested it.
> 
> 
> 
> What I'm a bit surprised about is that there's no `legacy_save` method distinction in the loader.
> 
> 
> 
> If that is so, then is the `legacy_save` parameter in `save` unnecessary? Or will it load only files saved in the new way now? If that does not "match", then this comment is blocking (as it would mean users cannot use `legacy_save` for loading, saving with that param becomes "write-only").

Let me test it again if the old save and load again works. But I think I run the test with the new and an older tensorflow version. If both work then everything should be fine or?

2024-03-11 23:21 UTC, fkiraly commented
> If both work then everything should be fine or?

Actually, what I was thinking, new `tensorflow` version with `legacy_save` on and off, and then try `load` twice. Btw, are we testing this somewhere?

2024-03-12 06:04 UTC, benHeid commented
This would result in the same execution path in the CI, since the legacy safe is only considered if the version is lower than 2.16.0. However in the CI pipeline we are installing the latest version

2024-03-12 13:50 UTC, fkiraly commented
So, then my question is, why do we need `legacy_save` at all - what user code is impacted? If `load` work the same whether this flag is set or not, then there's no user code we're breaking, and no change/deprecation is needed.

Or am I getting sth wrong?

2024-03-12 16:15 UTC, yarnabrina commented on sktime/classification/tests/test_base.py
> +        assert full_dummy.optimizer.variables == deserialized_full.optimizer.variables
@benHeid sorry to opening this resolved question once more, but I see tests do not have to use the latest verions always if triggered from `classification` or `network` or `regression` (or `dl` - won't happen in new CI). Those have upper bounds set as 2.14, probably based on latest version at time of creation (though why inclusive I can't remember).

If those upper bounds are no longer necessary, may be those can be updated to recent ones.

2024-03-12 16:43 UTC, fkiraly commented
Ah, I see. Yes, that makes sense.

2024-03-12 16:58 UTC, benHeid commented
> * will this then imply a new lower bound on tensorflow? I would guess not, since the new behaviour makes a version distinction

No, we do not need a new lower bound. Old versions and the new version are working.

> * "it might be the case that it breaks if the model is stored differently" - is this really the case, if `load` works no matter what?
I haven't tested it. My assumption is: From sktime side, it should work since I just look which files are available and depending on that the model is loaded. However, I am unsure if the new tensorflow version would load models that are stored using and older version.

2024-03-12 17:33 UTC, benHeid commented on sktime/classification/tests/test_base.py
> +        assert full_dummy.optimizer.variables == deserialized_full.optimizer.variables
Oh okay... This explains why this failure is only occurring on mlflow and pandas 1. In these cases, tensorflow 2.16.1 is installed.  I can try to execute everything without that bound. -> All extras is installing tensorflow without any bounds. This seems to be a bit inconsistent.

2024-03-13 16:18 UTC, fkiraly requested changes
Hm, with the version bound removed, it fails now.

I'll make a separate PR that adds bounds `tf<2.6.0`

2024-03-13 19:04 UTC, fkiraly commented
Here: https://github.com/sktime/sktime/pull/6117

2024-03-13 21:44 UTC, benHeid commented
It seems that the errors are related to the save/load of the deep learning based regressors.. I try to fix them

2024-03-14 12:44 UTC, fkiraly approved these changes
I see - looks like they are fixed now!

To confirm quickly, this means we no longer need #6117 , right?

2024-03-14 15:22 UTC, yarnabrina commented
> I see - looks like they are fixed now!
> 
> To confirm quickly, this means we no longer need #6117 , right?

I'm very sorry, I didn't see this and merged that one to not see failures in other PR's. Now that leads to conflicts in this one, apologies.

2024-03-15 06:25 UTC, benHeid commented
Should I resolve the conflicts or do should we revert the other PR?

2024-03-16 12:22 UTC, fkiraly commented
> Should I resolve the conflicts or do should we revert the other PR?

I would say, the clean way is resolving the conflicts *by* reverting the other PR as part of this one.

2024-03-16 13:20 UTC, fkiraly requested changes
Makes sense.

Minor things, non-blocking (I can fix these):

* warning and effective path check should be located in the public function
* typo in warning, legacy_save, not legacy_warning
* duplication depending on serialization_format, this is not introduced in this PR but impacted. I would refactor it to a single call of `_serialize_using_dump_func`, the branch affecting only the package that is being referenced. I.e., `if serialization_format == "cloudpickle": serial_pkg = cloudpickle`

2024-03-16 19:14 UTC, fkiraly approved these changes

2024-03-16 19:18 UTC, merged