[ENH] test parameters for RocketRegressor
sktime/sktime pull request #6149
Opened 2024-03-17 12:30 UTC by iaryangoyal

Reference Issues/PRs
Issue - https://github.com/sktime/sktime/issues/3429

Please use keywords (e.g., Fixes) to create https://github.com/sktime/sktime/issues/3429 to the issues or pull requests
you resolved, so that they will automatically be closed when your pull request
is merged. See https://github.com/blog/1506-closing-issues-via-pull-requests.
If no issue exists, you can open one here: https://github.com/sktime/sktime/issues

What does this implement/fix? Explain your changes.
I've added another dictionary to the list returned by the method, where num_kernels is set to a different value (in this case, 100). This provides a second parameter set for testing the RocketRegressor estimator.

2024-03-17 13:12 UTC, iaryangoyal commented
@fkiraly Please review this of adding two test parameters in RocketRegressor and merge the same

2024-03-17 14:18 UTC, fkiraly requested changes
Sure. Kindly address my review comments on the added test parameters from the other PR.

2024-03-18 04:20 UTC, iaryangoyal commented
Sure sir,
talking about review comments on other PR first is Some requests:

1. can you cover the other parameters too? (except n_jobs, random_state)
    I will work on them to see if this PR is correct to merge in the main or not this will help me.
2. there is no need for the "if", the test framework interprets condition-less returns as the default.
    I have removed the "if" statement and returned the two test parameters directly.

2024-03-18 12:40 UTC, fkiraly commented
Could you also kindly resolve the conflict in the file?

2024-03-18 13:46 UTC, iaryangoyal commented
> Could you also kindly resolve the conflict in the file?

I have solved the conflict in the file

2024-03-19 17:57 UTC, yarnabrina requested changes

2024-03-19 17:57 UTC, yarnabrina commented on sktime/regression/kernel_based/_rocket_regressor.py
> +        """Return testing parameter settings for the estimator
Why are we removing the period at line end and the new line? Did you check pre-commit locally? Are you not getting errors from pydocstyle?

2024-03-19 17:57 UTC, yarnabrina commented on sktime/regression/kernel_based/_rocket_regressor.py
> +
Usually, it's recommended to have one empty line at end. It seems now there are 3: one was already there plus you are adding two more.

I'm not sure if your local pre-commit setup is correct. Can you please follow the setup and run the following command against your branch?

```
pre-commit run --all-files
```

It's very likely going to modify the file you changed. If it modifies other files too, please ignore those changes and undo before staging and committing this specific file.

2024-03-19 22:06 UTC, fkiraly commented on sktime/regression/kernel_based/_rocket_regressor.py
> +        return [{"num_kernels": 20}, {"num_kernels": 100}]
(yes)

2024-06-08 22:54 UTC, fkiraly commented
I fixed the linting issues so we can merge this.

2024-06-08 22:54 UTC, merged