[Fix] resolve duplication in KNeighborsClassifier and KNeighborsRegressor
sktime/sktime pull request #6504
Opened 2024-05-31 10:25 UTC by Z-Fran

#### Reference Issues/PRs
https://github.com/sktime/sktime/pull/6217#pullrequestreview-1969913623

#### What does this implement/fix?
create a new class `KNeighborsSklearnAdapter` to resolve duplication in KNeighborsClassifier and KNeighborsRegressor

#### What should a reviewer concentrate their feedback on?
1. whether the path of the new file is appropriate
2. whether the name of the new class is appropriate

2024-06-01 13:23 UTC, fkiraly requested changes
Interesting, thanks! I think this is a robust refactor, as you say we need to think about the right target location.

Might I suggest to split the adapter in two, and move the parts as follows:

* the distance adapter logic should to in `dists_kernels/base/adapters/_sklearn`
* the common `_fit`, `predict` features should go in `base._panel.knn` (and submodules thereof)

2024-06-02 19:59 UTC, Z-Fran commented
I have moved the distance adapter logic to `dists_kernels/base/adapters/_sklearn` and moved `_fit`, `predict` features to `base._panel.knn`. But I don't know how to organize `base._panel.knn`. well. I need some of your suggestions. @fkiraly

2024-06-05 15:57 UTC, fkiraly commented on sktime/base/_panel/knn.py
> +class BaseKnnTimeSeriesEstimator:
make this a private class, start it with underscore, or it might be picked up by the tests.

2024-06-05 15:58 UTC, fkiraly commented on sktime/dists_kernels/base/adapters/_sklearn.py
> +class _SklearnKnnAdapter:
not related to distance, so I would call it `DistAdapter`

2024-06-05 15:59 UTC, fkiraly commented on sktime/dists_kernels/base/adapters/_sklearn.py
> +class _SklearnKnnAdapter:
it's also a mixin, so how about `_SklearnDistMixin`

2024-06-05 15:59 UTC, fkiraly commented on sktime/dists_kernels/base/adapters/_sklearn.py
> +    _tags = {
not an estimator, so no tags needed

2024-06-05 16:00 UTC, fkiraly commented on sktime/base/_panel/knn.py
> +    _tags = {
mixin, so no tags needed

2024-06-07 08:57 UTC, Z-Fran commented
Hi @fkiraly ,  I have finished your suggestions.

2024-06-08 18:13 UTC, fkiraly commented on sktime/classification/distance_based/_time_series_neighbors.py
> +        self._X = X
why are we doing this?

2024-06-08 18:14 UTC, fkiraly requested changes
looks good!

One minor question, why are we writing `self._X`? That does not look like a refactor, but a change in logic.

2024-06-08 18:53 UTC, Z-Fran commented
> looks good!
> 
> One minor question, why are we writing `self._X`? That does not look like a refactor, but a change in logic.

Oh, it's related to [#6515 ](https://github.com/sktime/sktime/issues/6515#issuecomment-2144002401). I wrote it when debugging. I've deleted it.

2024-06-08 19:01 UTC, fkiraly commented
Ah, I see! I wuld suggest, let's try to fix that (if at all) in another PR, and add tests - this PR should be a pure refactor, i.e., not changing logic.

2024-06-09 22:56 UTC, fkiraly approved these changes
Looks good to me now!

2024-06-11 01:23 UTC, Z-Fran commented
Hi, @fkiraly , could it be merged?

2024-06-11 11:28 UTC, fkiraly commented
Yes, that´s the plan. Just wanted to give other core devs some time to react. Best practice is 5 working days.

2024-06-15 14:35 UTC, merged