[ENH] Hierarchical scitype support for polars
sktime/sktime pull request #6697
Opened 2024-07-01 06:36 UTC by pranavvp16

This PR is complete with checks and conversion functions for Hierarchical scitype for polars, with scitype name `polars_hierarchical`. PR #6485 and #6552 needs to be merged before this

2024-09-06 12:10 UTC, pranavvp16 commented
@fkiraly This PR is also ready to merge as #6552 is merged now. I have also updated this branch with

2024-09-07 12:39 UTC, fkiraly commented on sktime/datatypes/_panel/_check.py
> +    def check_polars_panel(
why are you changing this? The arg `panel` should actually be removed.

2024-09-07 12:40 UTC, fkiraly requested changes
Thanks for the reminder!

* I think the "examples" part whould reintroduce the failure of `sktime` on `polars` described here - https://github.com/sktime/sktime/issues/7056 - can you kindly fix that?
* the checker should have only the same arguments every other checker has. Internally, of course, it can call the more general checker.

2024-09-24 10:07 UTC, fkiraly requested changes
@pranavvp16, I have now updated `main` with the handling of the soft dependencies in examples, and also adapted the `_examples` file - could you kindly have a look?

2024-09-25 04:25 UTC, pranavvp16 commented
Meanwhile I was thinking for a smaller fix the new `datatypes` example refactor solves this issue more efficiently. I have addressed the remaining comments in this PR, can you kindly review it @fkiraly .

2024-09-25 06:35 UTC, fkiraly approved these changes
Looks good to me now, if you are also happy with it.

2024-09-25 07:32 UTC, fkiraly approved these changes

2024-09-25 07:47 UTC, merged