Type hints Fix
sktime/sktime pull request #6743
Opened 2024-07-10 11:15 UTC by ZhipengXue97

## Description
Fix Several type check warnings reported by Pyre@Google, which were outdated after code modifications.

## Detail
1. update the argument `to_type` in function `convert` from `str` to `Union[str, List[str]]`, since it could be str or list of str after commit 0094f868c2930ceb3f246972dd34d15348469809
2. update the argument `as_scitype` in function `convert` from `str` to `Optional[str]`, since it could be str or None after commit 105ad4c4411fefbdc8ad587727f666a41a47ad1c 
3. update the argument `store_behaviour` in function `convert` from `str` to `Optional[str]`, since it could be str or None after commit b02a98b55c30b9fee3ab82af4c2636b03472022
4. update the argument `to_type` in function `convert_to` from `str` to `Union[str, List[str]]`, since it could be str or list of str after commit b6e02967998e9d9a55dff9f9e28f538e7f51d558
5. update the argument `as_scitype` in function `convert_to` from `str` to `Optional[Union[str, List[str]]]`, since it could be str ,None, or list of str after commit b6e02967998e9d9a55dff9f9e28f538e7f51d558
6. update the argument `store_behaviour` in function `convert_to` from `str` to `Optional[str]`, since it could be str or None after commit b02a98b55c30b9fee3ab82af4c2636b03472022

2024-07-10 16:04 UTC, yarnabrina requested changes
Thanks for your contribution. I've made a suggestion below. Once you make that change and @fkiraly is okay, this can go in this release. Or we'll do in the next one.

I'll note however that a huge part of sktime codebase is not type hinted, or sometimes marked incorrectly. I'm slightly surprised that pyre caught only one occurrence.

2024-07-10 16:29 UTC, ZhipengXue97 commented
We are trying to develop a tool to update the type hints based on the code modification such as commit, to avoid false positive warnings from type checker, this PR is fixed by our tool based on the previous commit.

Actually, there are still many warnings like `argument`: `type` = `None`, which should be corrected to `Optional[type]`. However, I'm not sure if these corrections are necessary.

2024-07-11 15:58 UTC, fkiraly requested changes
Thanks!

I'm copying a stackoverflow post (from here https://stackoverflow.com/questions/51710037/how-should-i-use-the-optional-type-hint) regarding the use of `Optional` when the default is `None`:

![image](https://github.com/sktime/sktime/assets/7985502/af9399a6-ea98-4e94-9ef7-bbb38bf3ab69)

In this case, it is considered "obvious" that the arg is `Optional`, and adding this just lowers readability, so I would prefer not having `Optional` if the default is `None`. The remaining changes are valid, as the support for lists of str was added after the original type hints, and these were forgotten to be updated.

2024-07-11 18:19 UTC, yarnabrina commented
Sorry, but I'll argue against. [That same answer](https://stackoverflow.com/a/66922247) has a comment which directs to [PEP-484](https://peps.python.org/pep-0484/#union-types), which recommends explicit mention.

<img width="822" alt="image" src="https://github.com/sktime/sktime/assets/39331844/073ddacb-ad5f-4632-85f8-259436e35f70">

2024-07-11 19:06 UTC, fkiraly commented
I see. I take my comment back then. Seems like it was recommended for some time but no longer is.

2024-07-11 19:07 UTC, fkiraly approved these changes

2024-07-24 20:16 UTC, merged