[BUG] Fix bug when predicting segments from clasp change point annotator
sktime/sktime pull request #6756
Opened 2024-07-12 19:45 UTC by Alex-JG3

#### Reference Issues/PRs

Closes #6741.

#### What does this implement/fix? Explain your changes.

The `predict_segments` method was failing for change point detection algorithm because it was calling `segments_to_change_points` not `change_points_to_segments`.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Did you add any tests for the change?

No but it highlights the need for better annotation module tests. I will open a related issue.

#### Any other comments?

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-07-12 20:28 UTC, fkiraly requested changes
we should add a test - at least for clasp, better for all annotators

2024-07-13 11:41 UTC, Alex-JG3 commented
I am having a go at writing a test for this but there is another issue. When making the big changes to `BaseSeriesAnnotator`, I decided not to change the output format of `predict` for backwards compatability. So, we have the following:

```python
>>> from sktime.annotation.clasp import ClaSPSegmentation
>>> from sktime.utils._testing.annotation import make_annotation_problem
>>> X_train = make_annotation_problem(n_timepoints=10)
>>> print(X_train)
2000-01-01    1.508174
2000-01-02    2.079181
2000-01-03    1.923736
2000-01-04    2.180592
2000-01-05    1.000000
2000-01-06    1.957757
2000-01-07    2.144369
2000-01-08    3.097359
2000-01-09    2.145177
2000-01-10    4.231551
Freq: D, dtype: float64
>>> clasp = ClaSPSegmentation(n_cps=1)
>>> clasp.fit(X_train)
>>> points = clasp.predict_points(X_train)
>>> print(points)
Freq: D, dtype: float64
0    0                                                                                                                                                                        
>>> clasp.change_points_to_segments(points, start=X_train.index[0], end=X_train.index[-1])
Traceback (most recent call last):
  File "/home/alex/documents/sktime/main.py", line 13, in <module>
    clasp.change_points_to_segments(points, X_train.index[0], X_train.index[-1])
  File "/home/alex/documents/sktime/sktime/annotation/base/_base.py", line 644, in change_points_to_segments
    index = pd.IntervalIndex.from_breaks(breaks, copy=True, closed="left")
  File "/home/alex/documents/sktime/.venv/lib/python3.10/site-packages/pandas/core/indexes/interval.py", line 274, in from_breaks
    array = IntervalArray.from_breaks(
  File "/home/alex/documents/sktime/.venv/lib/python3.10/site-packages/pandas/core/arrays/interval.py", line 463, in from_breaks
    return cls.from_arrays(breaks[:-1], breaks[1:], closed, copy=copy, dtype=dtype)
  File "/home/alex/documents/sktime/.venv/lib/python3.10/site-packages/pandas/core/arrays/interval.py", line 544, in from_arrays
    left, right, dtype = cls._ensure_simple_new_inputs(
  File "/home/alex/documents/sktime/.venv/lib/python3.10/site-packages/pandas/core/arrays/interval.py", line 352, in _ensure_simple_new_inputs
    raise TypeError(msg)
TypeError: category, object, and string subtypes are not supported for IntervalIndex
```

The output from `predict_points` is a list of change points in terms of `iloc`, the change points should be datetimes not integers. Since the predicted change points are integers we cannot use `change_points_to_segments` since this method expects integers and datetimes cannot be compared.

## Possible Solutions

1. Change the output type of `predict` to match the type of the index of `X`. Would this require a deprecation warning?
2. Only support integer change points for clasp so skip raise an error in clasp if `X` has in index data type other than integer.

I prefer option 1.

2024-07-14 16:44 UTC, fkiraly commented
what is the current behaviour? I would suggest to keep it downwards compatible. I also did not think about the loc/iloc issue here, loc indeed seems more general. Are you saying that currently the return is always iloc?

Either way, I think we should start thinking about a test suite for systematic testing, the devil is in the details.

2024-07-15 17:31 UTC, Alex-JG3 commented
The current behaviour is that clasp specifically returns `iloc` rather than `loc`. That was done to keep to keep its previous behaviour when making the changes in #6265. Eventually, I would like to move all annotators away from using `iloc` to `loc` but agree that doing proper deprication is essential.

Here is an example of `iloc` predictions from clasp.

```python
>>> import pandas as pd
>>> from sktime.annotation.clasp import ClaSPSegmentation
>>> index = [i * 5 for i in range(100)]
>>> x = pd.Series([1] * 50 + [5] * 50, index=index)
>>> clasp = ClaSPSegmentation(n_cps=1)
>>> clasp.fit(x)
>>> points = clasp.predict_points(x)
>>> print(points)
0    52
dtype: int64
```

The returned index of the change point should be a multiple of 5 if `loc` were used.

Do you think we should start the rigorous test suite in this MR? I think it would be better in a separate issue and MR.

I will write a simple test just for clasp for the time being to see if that is sufficient to satisfty this issue with the aim to start of more rigorous test suite in a different issue and MR.

2024-07-17 21:04 UTC, fkiraly commented
> Do you think we should start the rigorous test suite in this MR? I think it would be better in a separate issue and MR.

Agree, better in a separate MR - let's start.
Shall we chat in the Fri meeutp?

2024-07-17 21:04 UTC, fkiraly approved these changes

2024-07-18 18:26 UTC, Alex-JG3 commented
> Shall we chat in the Fri meeutp?

I can't do this Friday. Can we do next Friday?

2024-07-18 18:38 UTC, merged

2024-07-18 20:55 UTC, fkiraly commented
sure!