URLs changed on CRAN; updated _fpp3_loaders.py accordingly
sktime/sktime pull request #7084
Opened 2024-09-06 17:40 UTC by ericjb

FPP3 datasets are loaded from CRAN, using fixed URLs. CRAN updated two of the three URLs used by _fpp3_loaders.py. This PR updates the URLs accordingly (otherwise the functionality is broken.)

A reviewer can run the following code to test the change, if desired. 

```
import matplotlib.pyplot as plt
from sktime.datasets import load_fpp3
from sktime.utils.plotting import plot_series
y = load_fpp3('aus_production')['Beer']
fig, ax = plot_series(y)
plt.show()
```

2024-09-06 21:41 UTC, fkiraly requested changes
hm, we ran a full test suite today and this was not detected - are the tests covering success of downloads properly?

(the request is to clarify, and if not, then we should add tests)

2024-09-06 21:42 UTC, fkiraly commented
we could also upload the data to the `sktime` huggingface, where they would be ensured to be stable

2024-09-07 13:34 UTC, ericjb commented
With help from GitHub Copilot, here is a sample test function to be added to the test suite. Please suggest changes or explain where this test function should be placed so that it becomes part of the "full test suite". Thanks

```
import requests

def fpp3_test():
    """Unit test function for _fpp3_loaders.py"""
    url_fpp3 = "https://cran.r-project.org/src/contrib/fpp3_1.0.0.tar.gz"
    url_tsibble = "https://cran.r-project.org/src/contrib/tsibble_1.1.5.tar.gz"
    url_tsibbledata = "https://cran.r-project.org/src/contrib/tsibbledata_0.4.1.tar.gz"

    urls = [url_fpp3, url_tsibble, url_tsibbledata]

    for url in urls:
        try:
            response = requests.head(url)
            if response.status_code != 200:
                return False
        except requests.RequestException as e:
            return False

    return True
```

2024-09-08 14:44 UTC, ericjb commented
I responded to this request with sample test. Please advise if this is an ok test and where to place it. Thanks

2024-09-08 20:20 UTC, fkiraly commented
Hm, looks good with one minor issue: if we do it this way, we would have to update the dataset URL in two places, and if one changes it in only one place (e.g., next time we need to update), the test will no longer work.

We should hence use `_get_dataset_url` in the test.

2024-09-09 08:13 UTC, ericjb commented
Good point about the duplication of the url's. Fixed. Good catch. Released.

2024-09-09 19:41 UTC, fkiraly approved these changes
Thanks.

2024-09-09 19:41 UTC, merged