Mapa forecaster
sktime/sktime pull request #7101
Opened 2024-09-10 07:54 UTC by phoeenniixx

This is just an implementation of `MAPAforecaster` that is still incomplete and SHOULD NOT BE MERGED.

This Draft PR is created so that this implementation can be reviewed by the developers.

2024-09-10 18:12 UTC, fkiraly commented
The soft dependency handling is now resolved - the failures look genuine, do you need help with these, or can you diagnose with `check_estimator`?

2024-09-12 07:09 UTC, phoeenniixx commented
I tired to fix some issues, but when I fix one thing, another gets broken ;-( 
Need some help to get around this.

2024-09-12 21:09 UTC, phoeenniixx commented
@fkiraly any suggestions?

2024-09-13 20:20 UTC, phoeenniixx commented
Still facing some issues

2024-09-13 20:38 UTC, fkiraly commented on sktime/forecasting/mapa.py
> +        self._y = None
`_y` and `_is_fitted` do not need to be set explicitly

2024-09-13 20:39 UTC, fkiraly commented on sktime/forecasting/mapa.py
> +        self._y = check_series(y).copy()
you do not need to `check_series` or `check_is_fitted`, this is also done by the boilerplate - have a look at the `forecasting_supersimple` extension template

2024-09-13 20:40 UTC, fkiraly commented on sktime/forecasting/mapa.py
> +        auto_ets = AutoETS(sp=ppyA, auto=True)
I suggest making the forecaster a hyper-parameter, with `AutoETS` as a default (i.e., if the param is `None`)

2024-09-13 20:40 UTC, fkiraly commented on sktime/forecasting/mapa.py
> +    def _infer_seasonal_period(self, y):
should this also be an "auto" seasonal setting in the hyperparameters?

2024-09-13 20:45 UTC, fkiraly requested changes
I have looked at the errors, and it looks like this is really a "deep layer" failure now, not an interface failure. I.e., something in the internal code that implements the logic is failing, and no longer "surface layer" things. In that sense, this is progress, nice!

As the different functions are only minimally commented, I cannot really say anything without reverse engineering the code, which is not a good state of it.

I would suggest:

* write full docstrings for each of the lowest level functions, e.g., `statetrnaslate`, `mapacalc`, `mapacomb`, etc - with complete parameter list, type, description, assumes, guarantees.
* write individual tests for simple cases of inputs and outputs

One high-level guess is that the assumptions on format of input data, or the forecasting horizon, passed by the `sktime` boilerplate to the inner layer, do not fit with what those methods are assuming.

Further, if this is machine translation of existing R code, or copied from somewhere, I would suggest to (a) ping the author, and (b) add the GitHub ID of the author in the `authors` tag.

2024-09-13 21:02 UTC, phoeenniixx commented
I will try to write the code from the scratch and see if something that I might have messed up while debugging that everything is falling out of place. And would add the link of the R package and its author in the docstring

2024-09-13 21:32 UTC, fkiraly commented
> I will try to write the code (again) from the scratch and see if something that I might have messed up while debugging that everything is falling out of place.

I would strongly suggest adding unit tests with a comple expected inputs and outputs for all the small functions!
If you are modelling this on the R code, you can generate these examples using the R functions.

This is such a complex module with so many moving pieces, I would consider it essential for it to fit together, otherwise a small error can propagate through everything.

2024-10-01 16:35 UTC, phoeenniixx commented
Hi, The main issue I am facing is when I try `check_estimator` on the class
`Could not convert index to pd.DatetimeIndex. Please provide a datetime-compatible index.`
although I have implemented `_ensure_datetime_index()` (see line 80)

Maybe some 'internal' error or am I missing something?

2024-10-01 20:36 UTC, fkiraly requested changes
I think the key issue with thie PR is setting the tags - have a look at the `forecasting_supersimple` template.

Importantly, `python_dependencies` should be set and include `statsmodels` etc.

2024-10-02 19:19 UTC, phoeenniixx commented
Hi @fkiraly, please have a look at the fails

2024-10-03 19:07 UTC, fkiraly commented
This looks like a genuine failure in the logic of the code.

Have you understood what causes it? You need to debug and add tests.
Above, I have already suggested to test the individual functions.

When you debug, you should identify which place is actually failing. You should use the python traceback or a step-through approach. Let us know if you need help or pointers on how to debug or how to write tests.

2025-01-08 13:24 UTC, closed without merging