[ENH] window based time series segmentation via clustering
sktime/sktime pull request #7207
Opened 2024-09-30 18:26 UTC by Ankit-1204

#### Reference Issues/PRs
Implements #7142 

#### What does this implement/fix? Explain your changes.
Implements window based segmentation via clustering default being KMeans and window size=3

2024-09-30 18:35 UTC, Ankit-1204 commented
Alright, So Second ever pull request, wasn't aware all previous commits would also show up.

So up till now, I have tried to implement the non overlapping window part of the segmenter, 

- created a list of subseries of size of the window, Incase the size of Input was not a multiple of window size, I padded the last segment with (I could use some advise here incase this was wrong approach)
- After that I flattened each subseries, this I did mainly to handle multivariate time series, (again this might not be the correct approach so I could use some advise)
- After Clustering, assigned the clusters to each row.

@fkiraly any suggestions to improve my approach?

2024-10-03 10:19 UTC, fkiraly commented
> Alright, So Second ever pull request, wasn't aware all previous commits would also show up.

I see - you need to update your fork and create a new branch for a clean workflow.

Alternatively, you can update your fork and merge `main` into your branch, that should also resolve it.

2024-10-03 10:21 UTC, fkiraly requested changes
Nice!

For the algorithm, I was suggesting to use an `sktime` clusterer for the windows. I think it makes sense to allow *both* sklearn and sktime clusterers, but it should also support sktime clusterers.

2024-10-11 12:19 UTC, Ankit-1204 commented
@fkiraly 
- I implemented Overlapping window segmenter, i have used overlap variable(default false) to decide whether overlapping will be done. 
- Also incase of overlapping, I have used step size(default 1) to define the steps that each window will move, for non overlapping this was just the window_size.
- I have provided return_segments(default true) to decide if it will just return the segments or else it will return the aggregate based on majority rule.

I have not yet implemented the sktime clusterer for Overlapping segments, I could do that, i just wanted to check if my above approach was fine. Although I was wondering given the nature of data how useful the sklearn cluster would be

2024-10-26 17:26 UTC, Ankit-1204 commented
> Nice! We should also add an sktime clusterer to the test parameter sets.

@fkiraly should I create like a test file or add another test case in the wclust.py file itself.  Also, I actually tried using TimeSeriesKMeans as the test clusterer, but it required me to import numba and when i pushed the change, i received an error on the checks here.
Any idea on how i should proceed?

2025-01-02 09:07 UTC, closed without merging

2025-01-02 15:17 UTC, fkiraly commented
@Ankit-1204, why did you close or delete this? This was almost done.

2025-01-02 15:27 UTC, fkiraly commented
I restored the deleted branch here, in case this was an accident:
https://github.com/sktime/sktime/pull/7595

2025-01-02 16:00 UTC, Ankit-1204 commented
ah damn sorry, hadn't looked at this in some time and I think i accidently deleted it. I'll finish it up soon.