[DOC]: add newer patterns to handle unequal length and multivariate data in tutorial
sktime/sktime pull request #7362
Opened 2024-11-04 18:43 UTC by PranavBhatP

#### Reference Issues/PRs

Fixes: #7237 

#### What does this implement/fix? Explain your changes.

Adds the new patterns to deal with unequal length and multi-variate data into the classification tutorial.
#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

Quality and relevance of added documentation, open to feedback.

#### Did you add any tests for the change?

No.
#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-11-10 02:44 UTC, PranavBhatP commented
hi @fkiraly, can you review the changes to the tutorial notebook, wanted to see if I should add anymore changes to the notebook,

2024-11-10 09:02 UTC, fkiraly requested changes
Nice! I think we could merge this and it would already be a great improvement.

Some smaller comments:

* typographically, names of classes should be enclosed between backticks, like `IndepDist`, that way they appear in code font
* at the start, could you add a math explanation or reference (or both) to explain the difference?
* for more details on distances and composites, a pointer to notebook 6 might be good
* I would also add a third method: some estimators can deal with multivariate data natively, this is recorded in the capability tag (see section 2.3 below how to search). This should perhaps be the first method you explain.
* the first vignette uses two aggregation functions - sum and mean - which are very similar but double the amount of lines. I would suggest, show only one of these first, and mention how you would switch the aggregation function only.

2024-11-10 13:38 UTC, PranavBhatP commented
Sure! I'll add these changes.

2024-11-12 17:53 UTC, PranavBhatP commented
@fkiraly , I've added the requested changes.

2024-11-13 18:40 UTC, fkiraly commented
Great!

Best practice: click on the round arrow to re-request a review
![image](https://github.com/user-attachments/assets/be197e0b-3214-4711-902d-c5cdf628aa3a)

2024-11-13 19:11 UTC, fkiraly commented
Code formatting guide:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html

2025-02-01 12:28 UTC, fkiraly approved these changes
Thanks. I have shortened the text a little bit.

I am also noting that the additions address only *multivariate* data, not unequal length data. The PR descrpition has been updated accordingly.

2025-02-01 12:49 UTC, merged