[DOC] provide proper mathematical description in docstring of sliding window splitter.
sktime/sktime pull request #7376
Opened 2024-11-08 17:47 UTC by keitaVigano

#### Reference Issues/PRs

Fixes #7196 

#### What does this implement/fix? Explain your changes.

I wrote a better documentation for this splitter.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

Making sure that the documentation is written correctly.

#### Did you add any tests for the change?

No.

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-11-09 08:39 UTC, fkiraly requested changes
This is great and already a significant improvement!

Only small requests for improvement:

* the docstring should say that there is only a single pair of training/test window, because splitters could have multiple.
* the docstring should say which indices exactly are in the training set. Currently only a "starting point" and "end point" are mentioned.
* what happens if `fh` contains negative values? That would result in an invalid split, would it not?
* in the example, I would also simply list the numbers or indices corresponding to the picture, for maximum clarity.

2024-11-09 18:09 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    .. math:: [t_{N-fh[-1] - w}, \ldots, t_{N-fh[-1] - 1}]
is this correct? That is, is the splitter `iloc` rather than `loc` based? Good to know!

2024-11-09 18:11 UTC, fkiraly requested changes
Great, this has added the required level of detail!

However, something cannot be correct here, since the `window_length` claims it can be `timedelta`. It is not clearly stated what happens when `window_length` is `timedelta`. That would be inconsistent with the `int` case as well.

Could you kindly double check that the window applies to `iloc`, if the `window_length` is `int`, and whether it is `loc` or what else happens if it is `timedelta`?

2024-11-13 08:45 UTC, fkiraly commented
ready for a review?

2024-11-13 18:19 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    the training windows will be all indices in the intervals
*the inverval*, no? a single interval?

2024-11-13 18:19 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    `the size of the time series - fh[-1] - 1`,
length, not size, right?

2024-11-13 18:20 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    .. math:: [t_{N-fh[-1] - w}, \ldots, t_{N-fh[-1] - 1}]
can you confirm that fh is in the index and not subtracxted from $t_N$ instead?

2024-11-13 18:20 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    **Important Notes:**
leave a newline, or the bullet point list will not display. Check the rendering by looking at "details" near the readthedocs CI element.

2024-11-13 18:20 UTC, fkiraly commented on sktime/split/singlewindow.py
> +    - `SingleWindowSplitter` uses positional indexing (`iloc`) for the training and
for in-line code, use double backticks

2024-11-13 18:21 UTC, fkiraly requested changes
Nice! Left some comments.

2024-11-21 21:25 UTC, keitaVigano commented
@fkiraly Could you please review this?

2024-11-23 14:32 UTC, fkiraly approved these changes
Brilliant! Thanks!

Sorry for the delay.

2024-11-23 16:07 UTC, merged