[ENH] Add skchange estimators
sktime/sktime pull request #7458
Opened 2024-11-28 01:09 UTC by ShivamJ07

#### Reference Issues/PRs

Please see https://github.com/sktime/sktime/issues/7351 for more details.

#### What does this implement/fix? Explain your changes.

This is a **WIP**. Just added the `moving_window` for now, other estimators will follow in future commits.

- This is based on the following [euroscipy code example](https://github.com/sktime/sktime-tutorial-euroscipy2024/blob/main/notebooks/04_customization.ipynb).
- This PR will add skchange estimators to the sktime estimator registry via the placeholder record pattern.
- Imports for models in this newly added folder will be redirected to skchange (provided that the required version of skchange is installed).

#### What should a reviewer concentrate their feedback on?

- What should the expected behavior be if a user attempts to import `sktime.detection.skchange.moving_window` but does not have the required version of skchange installed?

#### PR checklist

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

2024-11-28 01:45 UTC, ShivamJ07 commented on sktime/detection/skchange/moving_window.py
> +    "skchange.change_detectors.moving_window", dependencies="skchange>=0.6.0"
Is there any direction on whether explicitly specifying the `skchange` dependency is necessary? If so, what should be the version? How would we handle the case where user has a version mismatch the sktime placeholder is imported instead?

2024-11-28 14:37 UTC, fkiraly requested changes
Thanks, looks great!

Some notes:

* also ensure adding the estimator(s) to the API reference, in `docs/api_reference`
* the `dependencies` tag in the `_placeholder_record` needs to be set only when the tag is not set. In this case, I would simply set the tag `python_dependencies="skchange>=0.6.0"`.
* The docstring should be identical with that in `skchange`. I do hope there is a more complete docstring?
    * With one potentila exception: in the summary line, we should also add the qualifier "from `skchange`", and in a second line give the full path in `skchange`. This is read by the doc generator and displayed in the table in the API reference - so those summary positions give credit to `skchange` and its developer(s).
* The `__init__` should also be copied, at least with the full set of arguments, because this is read by the doc generator

Have a look at `HierarchicalProphet` for a no-exceptions example

2024-12-01 11:45 UTC, fkiraly commented
Thanks! To expedite this for the presentation, I will take this PR and finish it.

2024-12-01 17:50 UTC, ShivamJ07 commented
> Thanks! To expedite this for the presentation, I will take this PR and finish it.

Sounds good, let me know if I can be of any help.

2024-12-01 23:40 UTC, merged