[BUG] Fix inconsistency in `_online_shapelet_distance` std computation
sktime/sktime pull request #7499
Opened 2024-12-09 09:49 UTC by fnhirwa

this PR fixes the inconsistency where the `_online_shapelet_distance`   during `std` computation, there was a case where variance was being used as std and another formula used actual std.

fixes https://github.com/sktime/sktime/issues/5480

2024-12-12 08:39 UTC, fkiraly requested changes
The fix looks reasonable, but we need to fix the tests as well.

2024-12-12 10:30 UTC, fnhirwa commented
> The fix looks reasonable, but we need to fix the tests as well.

sure will work on it as well

2025-01-30 13:15 UTC, fkiraly submitted a review, later dismissed

2025-01-30 14:27 UTC, fkiraly approved these changes

2025-01-30 15:16 UTC, merged