[ENH] Forecaster imputer for RecursiveReductionForecaster
sktime/sktime pull request #7535
Opened 2024-12-16 15:22 UTC by lenaklosik

#### Reference Issues/PRs
Fixes #7477 

#### What does this implement/fix? Explain your changes.
This proposal aims to introduce the capability to incorporate a `forecaster` into the imputation process within the `RecursiveReductionForecaster `(RRF). Specifically, it suggests allowing RRF to accept a forecaster as an initialization argument and to initialize the Imputer with` method="forecaster"` during the `fit`, `predict_in_sample`, `predict_out_of_sample `when a forecaster is provided. This feature would be a valuable enhancement, delivering greater flexibility and precision in managing missing values.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-12-18 20:25 UTC, fkiraly requested changes
Interesting addition!

May I suggest a different approach, from adding an argument?

I would suggest that `impute_method` can also accept a transformer, an arbitrary one.
If it is passed, then it is chained instead of the `Imputer(method=impute_method)`. This way, we keep the interface more flexible, and do not need to add a new argument.

The user can then pass `Imputer("forecaster", my_forecaster)` instead, to `impute_method`.

What do you think?

Also, we should add a test case to `get_test_params` for this extension.

2025-01-07 09:30 UTC, lenaklosik commented
Thank you for the feedback and the interesting suggestion!

I agree that allowing `impute_method` to accept an arbitrary transformer would indeed make the interface more flexible and eliminate the need to add a new argument. I will implement this in the code.

Here's how I envision the initialization based on your suggestion. Could you please confirm if this aligns with your expectations?

```python
# Example usage
lags = 12
forecaster = RecursiveReductionForecaster(estimator=XGBRegressor())
forecaster_imputer = Imputer(method="forecaster", forecaster=forecaster)

recursive_forecaster = RecursiveReductionForecaster(
    estimator=XGBRegressor(), window_length=12, pooling="local", impute_method=forecaster_imputer
)
```

I will also add a test case to get_test_params to cover this extension.

2025-01-15 18:30 UTC, fkiraly commented
yes, exactly! Apologies for the late response.

2025-01-15 19:06 UTC, fkiraly submitted a review, later dismissed
Looks good - I fixed the linting.

2025-01-15 19:29 UTC, fkiraly approved these changes
Great!

I also extended the idea to additional estimators: https://github.com/sktime/sktime/pull/7646

2025-01-15 20:38 UTC, merged