[ENH] Enable to use enbpi with native implemented bootstrap algorithms.
sktime/sktime pull request #7562
Opened 2024-12-22 18:48 UTC by benHeid

#### Reference Issues/PRs
fixes #7561

#### What does this implement/fix? Explain your changes.
Add the option to bootstrap algorithms to return the indices. Change the Enbpi forecaster so that it works with native bootstrapper by changing the internally expected interface.

#### Does your contribution introduce a new dependency? If yes, which one?

No 
#### What should a reviewer concentrate their feedback on?

* Are the deprecation cycles okay?
* Should a tag be introduced showing the possibility of the transformations to return indices? 

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

2025-01-14 12:46 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +                + "Please bass  TSBootstrapAdapter(MovingBlockBootstrap())"
typo, pass

2025-01-14 12:47 UTC, fkiraly requested changes
Looks reasonable to me.

But, thinking about downwards compatibility: is there a stringent reason to deprecate passing direct bootstrappers from `tsbootstrap`? We can still capture it and wrap it in the adapter, leading to no change in public behaviour.

2025-01-14 12:51 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +        if isinstance(bootstrap_transformer, BaseTimeSeriesBootstrap):
this inheritance check and import can be avoided by doing the type check, using a check for the tag `object_type == "bootstrap"`

2025-01-26 18:51 UTC, benHeid commented
@fkiraly Thanks for the review. I addressed the comments :)

2025-02-05 14:07 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +    >>> forecaster = forecaster.fit(y, fh=range(1, 12)) # Range is broken
what do you mean, range is broken - is there a bug?

2025-02-05 14:07 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +                + "sktime MovingBlockBootstrap in version 0.37.0."
oops, sorry, missed this before the release. The version now needs to change to 0.38.0.

2025-02-05 14:09 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +                + "If you want to use the current behavior"
Clearer perhaps: "For the current default behaviour after 0.37.0, pass bootstrap_transformer= ..."

2025-02-05 14:10 UTC, fkiraly commented on sktime/forecasting/enbpi.py
> +            },
let's keep the `tsbootstrap` test case too (append if dep is present)

2025-02-05 14:12 UTC, fkiraly requested changes
Sorry for missing this in time for 0.35.1.

Because of that, we need to change the message to point to 0.38.0.

You should also add release manager instructions on what exactly to change, prefaced by a comment `# todo: 0.38.0`, this should be as precise as possible to allow "mindless" execution.

2025-02-09 15:48 UTC, benHeid commented on sktime/forecasting/enbpi.py
> +    >>> forecaster = forecaster.fit(y, fh=range(1, 12)) # Range is broken
Was a note to me, that is now fixed. The original example was broken.

2025-02-09 15:48 UTC, benHeid commented on sktime/forecasting/enbpi.py
> +                + "sktime MovingBlockBootstrap in version 0.37.0."
Done

2025-02-09 15:50 UTC, benHeid commented on sktime/forecasting/enbpi.py
> +                + "If you want to use the current behavior"
Done

2025-02-09 15:56 UTC, benHeid commented on sktime/forecasting/enbpi.py
> +            },
Done

2025-02-15 09:17 UTC, fkiraly requested changes
Just wanted to merge the PR but discovered one more tag related issues, namely the introduction of `can_return_indices`.

* for consistency with current tags, can you please call it `capability:something`?
* for consistency with the current tag system, can you please add a full record class and add it to the tag reference API?
* we also need to think about extensibility and default values. What happens if a user has a transformer that complies with the interface but does not have the tag?
* Finally, why is this tag required? I am not entirely certain about the intended interface of yours, but do not all `sktime` transformers produce indices?

2025-02-15 09:31 UTC, benHeid commented
Let us first discuss the questions before I change the code.

> * we also need to think about extensibility and default values. What happens if a user has a transformer that complies with the interface but does not have the tag?

Then it would not be possible to use the enbpi algorithm or any other algorithm that relies on returned indices of the original time series.

> * Finally, why is this tag required? I am not entirely certain about the intended interface of yours, but do not all `sktime` transformers produce indices?

The tag is used to determine if the bootstrap algorithm is capable of returning the indices of the original time series to which each value belongs as extra column. The indexes of the original column are required for enbpi to work. So I need there to check if the bootstrap algorithm is capable of returning the indexes.

2025-02-15 09:34 UTC, fkiraly commented
> The tag is used to determine if the bootstrap algorithm is capable of returning the indices of the original time series to which each value belongs as extra column.

Is this not the same as the row index? If not, can you give a simple example for me to understand? Would be appreciated.

2025-02-15 09:39 UTC, benHeid commented
Imagine you have original time series
> index, value
> 1,         12
> 2,        13
> 3,        14

Now after applying some random shuffling with return_index it would look like

> index, value, resampled_index
> 1,         13,      2
> 2,        14,       3
> 3,        12,      1

It basically returns also the permuted original index.

2025-02-15 09:41 UTC, fkiraly commented
I see - what is the API convention for this to be returned?

2025-02-15 09:43 UTC, benHeid commented
An additional column in the dataFrame with name `resampled_index`. Would you prefer something else?

2025-02-15 10:21 UTC, fkiraly commented
> Would you prefer something else?

Do existing transformations in `sktime` already produce that?

2025-02-15 13:22 UTC, benHeid commented
> Do existing transformations in `sktime` already produce that?

No, they haven't produced it. Thus, I added the functionality that is controllable with the parameter `return_indices` (see the changes in `_mbb.py`)

2025-04-24 11:42 UTC, fkiraly requested changes
Before we merge this, I think we need to do two things:

* make clear the additional contract that the transformer needs to satisfy, in the documentation of the estimtaors accepting bootstrap transformers
* add a full tag record, not just a dict entry, that describes what the new tag means.
* the tag should probably also be named something more descriptive? `bootstrap_transformer` perhaps?

2025-04-27 12:58 UTC, fkiraly commented
> Are you meaning making it more explicit in the documentation of the EnbPI forecaster that the bootstrap transformers need to return indices to work together with the EnbPI forecaster?

Yes, and what concretely that means in terms of return objects of `transform`.

> Are you referring to the `bootstrap` tag? I am not introducing this in that PR. In this PR, I am introducing `return_indices`

I know, this was referring to the naming. Good tag names make clear what they mean, `return_indices` is not clear in that respect.

2025-04-27 13:24 UTC, benHeid commented
Thank you for the clarification. I addressed your comments :) Please check if the description are clear enough.

2025-05-11 17:49 UTC, fkiraly approved these changes
I've fixed a few issues with how the tag framework was used, now it should be compliant and ready to merge.

2025-06-01 14:14 UTC, merged