[BUG] Add missing frequencies to `load_forecastingdata`
sktime/sktime pull request #7575
Opened 2024-12-25 13:05 UTC by benHeid

#### Reference Issues/PRs
Closes #6388 

#### What does this implement/fix? Explain your changes.
* adds missing frequencies to the load_forecastingdata.
* ensures that the frequency information is not removed if the multi index is created.
* adds tests for the fixed issues.

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

Yes
#### Any other comments?

#### PR checklist

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

2024-12-26 09:03 UTC, fkiraly requested changes
The failures seem genuine and related? Or are these just in the same methods and unrelated to the PR?

2024-12-26 10:11 UTC, benHeid commented
These are timeouts from the downloads. These are large datasets that are loaded in these tests. Do we have a pytest timeout of 600sec? 

I fear that this is the reason for the failures. I can exclude those datasets from the tests.

2024-12-26 11:51 UTC, felipeangelimvieira commented
I believe the exit code in the 3.9 Ubuntu Latest CI workflow might be due to memory issues in the CI environment. Is there a chance that the data from the tests is not being freed from memory? Or could it be a single dataset requiring a significant amount of memory?

2024-12-26 20:38 UTC, benHeid commented
Would assume it is freed if the test is finished. However, there are 8 tests running in parallel. This might be the issue with the memory.

2024-12-29 09:13 UTC, benHeid commented
The hierarchical datastructure requires more memory than the tsf structure, since it requires index values for each value of each time series instead just indexes for each time series. 

Thus, I would propose to exclude very large datasets from the test `test_load_forecastingdata_hier` I have added. 

@fkiraly @felipeangelimvieira do you have any other ideas?

2025-01-04 14:55 UTC, benHeid commented
@fkiraly @felipeangelimvieira, I use only smaller datasets in the tests. The remaining errors are caused by #7600

2025-01-18 14:32 UTC, fkiraly approved these changes

2025-02-09 16:23 UTC, merged