[BUG] Data loader functions for datasets to return `y` with numeric `dtype`
sktime/sktime pull request #7588
Opened 2024-12-30 19:09 UTC by vedantag17

**Reference Issues/PRs**
Fixes #5431

#### What does this implement/fix? Explain your changes.

This fix adds an argument  `y_dtype` to the `load_dataset` functions that read from `.ts` files.
The default for the classification loaders is `str` and for regression loaders, it is `float`

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### Did you add any tests for the change?
No

#### PR checklist

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

2024-12-31 09:46 UTC, fkiraly commented on sktime/datasets/_data_io.py
> +        y_dtype : str, optional (default: 'str')
too many indentations

2024-12-31 09:50 UTC, fkiraly requested changes
Great!

May I request the following changes:

* have the new variable only in `load_UCR_UEA_dataset` and `_load_dataset`
* in calls where the default `y_dtype="str"` is used, do *not* set the kwarg explicitly - to minimize changed lines

2025-01-30 21:01 UTC, fkiraly commented
@felipeangelimvieira, it would be very kind if you could give this a quick look, given your recent work on the module - I will prioritize the dataset rework, but we will need to align this (or something similar) with the merged state, to fix the regression loaders.

2025-01-31 00:28 UTC, felipeangelimvieira requested changes
Thank you for the PR! Just left a comment

2025-01-31 00:28 UTC, felipeangelimvieira commented on sktime/datasets/_readers_writers/ts.py
> +        y = y.astype(np.float32)
Could we also add an statement `y.astype(y_dtype)` if `y_dtype` is instance of `np.dtype` ?

2025-01-31 17:42 UTC, vedantag17 commented on sktime/datasets/_readers_writers/ts.py
> +        y = y.astype(np.float32)
Just to confirm, should I add `if isinstance(y_dtype, np.dtype): y = y.astype(y_dtype)` before the existing if-elif statements?

2025-02-28 21:20 UTC, felipeangelimvieira submitted a review, later dismissed

2025-03-13 12:29 UTC, fkiraly requested changes
My comments have been addressed, so in-principle approved.

Though it seems this will fail code quality for numpydoc?

Unnecessary new lines are added in docstrings before "returns", could you kindly revert those?

2025-03-13 12:29 UTC, fkiraly commented
hm, why is this not failing numpydoc due to the two newlines before "returns"?

2025-03-13 13:01 UTC, vedantag17 commented
> Unnecessary new lines are added in docstrings before "returns", could you kindly revert those?

Can you point out where exactly the docstring is? Sorry, couldn't find it.

2025-03-13 13:34 UTC, fkiraly commented on sktime/datasets/_single_problem_loaders.py
> +
here

2025-03-13 13:34 UTC, fkiraly commented on sktime/datasets/_single_problem_loaders.py
> +
here

2025-03-13 13:34 UTC, fkiraly commented on sktime/datasets/_single_problem_loaders.py
> +
here

2025-03-13 13:34 UTC, fkiraly commented on sktime/datasets/_single_problem_loaders.py
> +
and here

2025-03-17 12:14 UTC, merged